### ISSUE TITLE
漢化mod bug

### ISSUE THREAD

**Issue by eroguma** [shabbywu/Battle-Brothers-CN#100]
[log.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/12101490/log.zip)

**Comment by Rayforward** [comment]
日志翻傻了，麻烦说明一下遇到了什么问题

**Comment by shabbywu** [comment]
> 日志翻傻了，麻烦说明一下遇到了什么问题

请问这份日志是在触发
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/e383b2dd-6519-47e4-a2c4-486317ba68aa)
这个问题后，马上保存的文件吗？

每次启动游戏都会刷新日志。

**Comment by Rayforward** [comment]
> > 日志翻傻了，麻烦说明一下遇到了什么问题
> 
> 请问这份日志是在触发 ![image](https://user-images.githubusercontent.com/5237578/254755334-e383b2dd-6519-47e4-a2c4-486317ba68aa.png) 这个问题后，马上保存的文件吗？
> 
> 每次启动游戏都会刷新日志。

着看着像是我上次报的你修了的问题的表现

**Comment by shabbywu** [comment]
@eroguma 辛苦补充以下 data 目录的截图，看下装了什么 mod. 截图前将“查看”方式切换至详细信息, 然后按名称排序。把排序后的列表和修改时间这两列都截图进来，我看下有什么 Mod

**Comment by Rayforward** [comment]
我今天也发现这样了：
19:22:40SQ
位置已输入：阿兹姆 沙布
19:22:42SQ
展示合约：狩猎野兽 (id: 10)
19:22:42Script Error
the index 'Contract' does not exist
Function:
_7ed3a9a60d3a40520e968646bbb6b198d6f9095e605e74b3ce980383a2fbf276 -> __main__ : 3
Variables:
this = Null
Function:
start -> scripts/contracts/contracts/roaming_beasts_desert_contract.nut : 66
Variables:
this = Table
Function:
setState -> scripts/contracts/contract.nut : 358
Variables:
_state = Table, this = Table
Function:
start -> scripts/contracts/contract.nut : 196
Variables:
this = Table
Function:
start -> scripts/contracts/contracts/roaming_beasts_desert_contract.nut : 54
Variables:
this = Table
Function:
showContract -> scripts/contracts/contract_manager.nut : 318
Variables:
_c = Table, this = Table
Function:
showContractByID -> scripts/contracts/contract_manager.nut : 297
Variables:
c = Table, _id = 10, this = Table
Function:
onContractClicked -> scripts/ui/screens/world/world_town_screen.nut : 445
Variables:
_data = 10, this = Table
19:22:44Resource
Unloading: music/worldmap_02.ogg
19:22:44SQ
展示合约：狩猎野兽 (id: 10)
19:22:44Script Error
the index 'Text' does not exist
Function:
getUIContent -> scripts/contracts/contract.nut : 479
Variables:
result = Array, this = Table
Function:
convertEventToUIData -> scripts/ui/screens/world/world_event_screen.nut : 166
Variables:
_event = Table, this = Table
Function:
show -> scripts/ui/screens/world/world_event_screen.nut : 95
Variables:
_withSlideAnimation = False, _event = Table, this = Table
Function:
showEventScreenFromTown -> scripts/states/world_state.nut : 355
Variables:
_playSound = False, _isContract = True, _event = Table, this = Table
Function:
showContract -> scripts/contracts/contract_manager.nut : 326
Variables:
_c = Table, this = Table
Function:
showContractByID -> scripts/contracts/contract_manager.nut : 297
Variables:
c = Table, _id = 10, this = Table
Function:
onContractClicked -> scripts/ui/screens/world/world_town_screen.nut : 445
Variables:
_data = 10, this = Table

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/45681350/5035b3bb-aec0-4daa-9445-3458affbd415)

**Comment by shabbywu** [comment]
我记得之前测试没问题的，可能是上次做的优化有问题。

**Comment by Rayforward** [comment]
[log.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/12107214/log.zip)


> @Rayforward log.html 压缩下上传看下

**Comment by shabbywu** [comment]
应该修复了，的确是这周的热更新里有个优化导致的问题。导致 this 变量变成了 null

**Comment by shabbywu** [comment]
已修复问题，关闭议题
