### ISSUE TITLE
运行了之后就乱码了，根本没法用啊

### ISSUE THREAD

**Issue by w602542704** [shabbywu/Battle-Brothers-CN#101]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/24689873/30bbd9fd-3cd2-4d35-bd17-59c2761ebb00)
这个版本的：: [https://github.com/shabbywu/Battle-Brothers-CN/releases/download/v20230703/bb-translator.exe.zip](http://jump2.bdimg.com/safecheck/index?url=rN3wPs8te/r8jfr8YhogjfUWFoMgIRa81Ja5wFIjHv9YUbjlLF6EQ4I8P6W3F6UfTl/SYU6AcJ2yJWDcm3s0HYSamBvcu5+GVtIQDSwIwQf81Pi8dj6U6NGARNnpaOyLe9JJIGMTk57uHM8LpSRjjv4nkuMGu+5yR1SYhoQSWhVqWG/flrqhhdaiBKhdxPaTNmqqg10e4QBzv1d1yhC5oTVMIR0HFmB7jSj8B7zHGgQLxjtnxBSqIXMYccudCXCsdj2oeHoEzTI=)

**Comment by duanshuiliu123** [comment]
这只是翻译器，还需要字体，就是zdata_font.zip这个文件，release找找有的

**Comment by Rayforward** [comment]
缺字体

**Comment by shabbywu** [comment]
详细使用说明见 https://battle-brothers-cn.shabbywu.cn/

需要字体才能展示中文
