### ISSUE TITLE
1.5.0.15 Script变动

### ISSUE THREAD

**Issue by Rayforward** [shabbywu/Battle-Brothers-CN#103]
![SharedScreenshot](https://github.com/shabbywu/Battle-Brothers-CN/assets/45681350/a07b3cb4-01be-4ae0-828b-9956ea8af502)

**Comment by shabbywu** [comment]
实际上就更新了几行代码，文本相关的就改了一个年份。2022年改成2023年

**Comment by shabbywu** [comment]
目前看来 exe无任何改动，应该只是重新签名了导致数字摘要变了。用内置的启动器还能凑合用，steam的启动器要更新下才能支持。

**Comment by Rayforward** [comment]
求有空更新一下Steam启动器呀，成就党要死了

**Comment by shabbywu** [comment]
上传了

**Comment by Rayforward** [comment]
> 上传了 https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v20230801
> 
> @Rayforward

好耶！多谢

**Comment by Rayforward** [comment]
不太行，新版本一打开就会把Battle-Brothers-CN文件夹同步回超古老状态……

**Comment by shabbywu** [comment]
点「更新翻译文本」可以恢复吗

**Comment by Rayforward** [comment]
> 点「更新翻译文本」可以恢复吗
点过了，依然是
【每一次】打开都会重置整个文件夹

**Comment by shabbywu** [comment]
我的锅，刚看到每次打开程序都会切到本地的 main 分支。我删一下这逻辑重新大包，稍等

**Comment by shabbywu** [comment]
更新了

**Comment by Rayforward** [comment]
似乎没啥问题了
