### ISSUE TITLE
某些任务点开卡死

### ISSUE THREAD

**Issue by a244729016** [shabbywu/Battle-Brothers-CN#105]
[log.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/12217564/log.zip)
比如地图种子XVHLDPKXHJ，出生地最近的城市点开第一个任务会卡死

**Comment by a244729016** [comment]
卡死的表述不太准确，就是点开任务但是任务窗口没有弹出，整个画面似乎不再接受点击事件。点esc能退出，但是重新点任务依然打不开任务窗口

**Comment by shabbywu** [comment]
要看下你的 Mod 列表，翻译器会往 `root_state.cnut` 注入一个函数 `RenderTemplate`, 从日志来看是注入的 `RenderTemplate` 函数没了。

排查方式:
1. 确认 zdata_cn.zip 里面有 `scripts/root_state.cnut` 这个文件

2. 确认 data 目录的 Mod 加载顺序
> 在 data 目录按名称排序，需要保证 zdata_cn.zip 是在最下面。
> 如果有名称排序比 zdata_cn.zip 更后的 mod 里面没有 `scripts/root_state.cnut 
 或 scripts/root_state.nut` 

3. 确保 `data` 目录没有名字叫 `scripts` 的文件夹
> 游戏的 Mod 加载顺序是优先使用未压缩的脚本文件

**Comment by a244729016** [comment]
感谢大佬！我进行了第三步操作，已经解决问题了
