### ISSUE TITLE
启动器翻译错误代码1

### ISSUE THREAD

**Issue by stig141** [shabbywu/Battle-Brothers-CN#114]
![R6LJ01~EX%_D65C7$F`BO{9](https://github.com/shabbywu/Battle-Brothers-CN/assets/18372822/775299f9-b71f-40a0-8902-38e91120dda0)
![RSI29 I8C8Z_C(4~ 1HQL8W](https://github.com/shabbywu/Battle-Brothers-CN/assets/18372822/6e26b266-f856-42e2-9e0a-4c1f07be5b6e)

**Comment by stig141** [comment]
重新下载了游戏，从第一个版本的启动器开始翻译也是错误代码1

**Comment by shabbywu** [comment]
辛苦提供下 mod 列表

**Comment by shabbywu** [comment]
@stig141 
将异常捕获了调整成打印日志，关闭离线模式后重新执行翻译会用最新的翻译脚本。应该不会再出现这个错误。

方便的话提供一下 Mod 列表(或者只提供 big_game_hut_contract 这个脚本), 我是挺想看下什么原因导致的

**Comment by stig141** [comment]
我没有找到这个文件在哪

**Comment by shabbywu** [comment]
没装过 mod 啊，那我自己琢磨排查下。我把异常捕获了，你重试看下行不行？代码热更的，不需要重新下载翻译器。

**Comment by stig141** [comment]
还是错误代码1，另外这个离线特权一直绑定不上一直是用户信息查询失败
![}FTB3WC$D6AUYRI{~FXFJ}W](https://github.com/shabbywu/Battle-Brothers-CN/assets/18372822/e896a887-cbc4-48bd-b244-0e19d28be49e)
![67 V81` NC~QNWJG9 J2JYV](https://github.com/shabbywu/Battle-Brothers-CN/assets/18372822/3dd572a0-0763-43f8-aae5-d8f3cf3e69be)

**Comment by stig141** [comment]
![NRA4N9S @ZXVZ1ZI$( %_Q3](https://github.com/shabbywu/Battle-Brothers-CN/assets/18372822/ec6c63dc-62e1-43e8-843a-7385c3c90e5c)

**Comment by shabbywu** [comment]
> 还是错误代码1

好吧，刚看了下改错分支了。刚重新发布了下。应该真修了。

**Comment by stig141** [comment]
可以正常用了 谢谢捏

**Comment by shabbywu** [comment]
> 这个离线特权一直绑定不上一直是用户信息查询失败

https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v20230823

**Comment by stig141** [comment]
![D3T~ 0%S_(439(%7U{DMU~A](https://github.com/shabbywu/Battle-Brothers-CN/assets/18372822/ba301e56-be04-4fc9-a4ed-a436fdebe2a8)

**Comment by shabbywu** [comment]
看起来是在腾讯云搭的代理有问题，拿到 access token 访问不了 github 的 api
我再弄一个不用代理的版本，应该就可以了。
