### ISSUE TITLE
经常在进入战斗的过程中提示script路径下的错误导致坏档

### ISSUE THREAD

**Issue by Downnnn** [shabbywu/Battle-Brothers-CN#116]
经常在进入战斗后，地形贴图变成色彩图块，只有大退才能恢复，而有的时候进入战斗就会弹出script路径下的多项错误导致游戏关闭，而当时的autosave档就没法读取了，只要读取游戏就会挂起，有其他人像我这样吗？这是翻译的文本文件错误了还是游戏本身出问题了？

**Comment by shabbywu** [comment]
地形贴图变成色彩图块，有可能是内存不够导致的贴图错乱.
这游戏的脚本机制会将接近2g的压缩包加载到内存，但是又因为游戏是 x86 架构的，最大可用内存4g, 程序能用得内存不足4g.

理论上可以尝试将游戏的视频从 data_001.dat 解压出来，不知道能不能改善。

**Comment by shabbywu** [comment]
从原理上分析，这游戏用的是 [physfs](https://github.com/icculus/physfs) 做脚本加载，会将 data_001 等压缩包读取到内存里。

所以理论上可以尝试将游戏的视频从 data_001.dat 解压出来放到 data 目录里, 这样 data_001.dat 起码可以少1g大小。
↑我没实操过，现在手上没有win电脑，所以不能验证。

**Comment by Downnnn** [comment]
内存是32G的，应该不存在物理内存不够的情况

**Comment by shabbywu** [comment]
"弹出script路径下的多项错误导致游戏关闭" 这个要看你安装的 Mod 列表，以及报错后的游戏日志。

**Comment by shabbywu** [comment]
未提供更多信息，无法跟进。/close
