### ISSUE TITLE
bb-translator 无法启动

### ISSUE THREAD

**Issue by zyj1616** [shabbywu/Battle-Brothers-CN#120]
开了离线模式后，打开bb-translator 没有ui界面，只有在background process里存在，一段时间后自动关闭，请问是什么问题，重装了游戏和bb-translator 都没有解决
![Screenshot 2023-12-04 233804](https://github.com/shabbywu/Battle-Brothers-CN/assets/35323786/c7360f77-a77a-471b-8f51-443fc5371157)

**Comment by zyj1616** [comment]
使用了https://www.nexusmods.com/battlebrothers/mods/647?tab=description 0.4.0.1 版本后可以重新启动

**Comment by shabbywu** [comment]
确认是有网络请求，这个月会更新个版本。

**Comment by shabbywu** [comment]
更新了个版本，可以试试 https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v20231206

**Comment by zyj1616** [comment]
新版本还是不行，没有报错我也不知道是哪里出了问题，不过rollback到4.0就可以正常运行，我怀疑是离线模式的问题。。点了之后就无法启动了

**Comment by shabbywu** [comment]
日常写 bug....刚发了 0.6.1 的更新.

- 修复游戏目录路径下有空格时，功能完全无法使用的问题
- 修复控制台日志输出乱码的问题
- 修复非 Unicode 编码下无法正常运行启动器的问题

**Comment by shabbywu** [comment]
如果 0.6.1 版本可以正常使用的話，我就会 Close 这个 issue 咯
