### ISSUE TITLE
现在还需要 data_cn.zip 与 data_font.zip这俩文件吗？

### ISSUE THREAD

**Issue by gy0851** [shabbywu/Battle-Brothers-CN#121]
我注意到0.6版本释出的包里没这俩文件，而且运行汉化工具后也提示unknown error occurred
还需要这个文件吗？

**Comment by shabbywu** [comment]
`zdata_cn.zip` 是翻译器生成的，这是汉化的核心文件。
如果你说的 **“unknown error occurred**” 是点 **执行翻译** 后的报错，辛苦提供下截图和操作系统等信息，顺便看下杀毒软件有木有拦截。
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/e6bfbd10-9112-42d8-a522-dd200cc0ce80)

---
另外的 `zdata_font.zip` 这文件现在不需要了，重写的启动器里内置了这文件。

**Comment by shabbywu** [comment]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/f2b0f739-7bcf-40c6-8480-e5f9efcd207f)
好家伙，我换一台电脑，也被杀毒软件拦了。。。我尽快看下怎样把这误报弄走。

**Comment by gy0851** [comment]
这是我的系统相关信息，不知道是否有所帮助
[
<img width="481" alt="11" src="https://github.com/shabbywu/Battle-Brothers-CN/assets/20726133/ba916717-755c-4d9c-b5ce-1b9e6397308c">
](url)
另外，我尝试将杀软关闭后依然提示如下
<img width="567" alt="22" src="https://github.com/shabbywu/Battle-Brothers-CN/assets/20726133/b4a61f0f-8cbd-409c-85c4-0ef2afa3b65a">
杀软的拦截信息中也没有找到相关信息
但在刚下好这个版本时第一次运行倒是提示成功了，不过进游戏后UI界面全是口口口口口，之后我尝试卸载游戏重新安装，并再次尝试使用汉化软件进行汉化时就出现了上图的情况，之后就再也没有成功过。

**Comment by shabbywu** [comment]
修复下来大概是有几个问题叠加起来导致的。
1. Windows 默认编码是 GBK, 这会导致控制台打印的日志乱码。
2. 游戏目录有空格，会导致启动命令报错...刚好我开发机的路径没空格，所以一直没测出来。
3. 报毒这个暂时没搞懂，重新编译了下杀毒软件就没拦了

**Comment by shabbywu** [comment]
“unknown error occurred” 应该是打了 Mod 导致同时存在  xxx.nut 和 xxx.cnut，然后翻译器有个 Bug 会导致生成的 zdata_cn.zip 里存在重复文件。这会导致 physfs(游戏的文件系统库) 异常。
这个问题也已经修复。

**Comment by gy0851** [comment]
虽然还是没成功，但幸运的是这回有了报错代码~大佬请过目
<img width="555" alt="11" src="https://github.com/shabbywu/Battle-Brothers-CN/assets/20726133/ea292d7f-2960-4b52-b113-455549c8f1d0">

**Comment by shabbywu** [comment]
把离线特权关了试试 Orz，我好像把离线功能搞挂了。

**Comment by gy0851** [comment]
好家伙，还真是离线特权的锅....关了以后一切正常。
感谢大佬的热心帮助！

**Comment by gy0851** [comment]
好家伙，还真是离线特权的锅....关了以后一切正常。
感谢大佬的热心帮助！
