### ISSUE TITLE
启动器报错

### ISSUE THREAD

**Issue by zhumangma** [shabbywu/Battle-Brothers-CN#122]
![1](https://github.com/shabbywu/Battle-Brothers-CN/assets/153610351/057b5379-00e3-4bd1-aa34-61dc5c6cdeca)
![2](https://github.com/shabbywu/Battle-Brothers-CN/assets/153610351/9325493f-a8ac-4657-9a52-e7c5162286c3)

**Comment by shabbywu** [comment]
游戏是 GOG 版本的，还是 Steam 版本的。
看日志应该点的是 GOG 版本的启动。

**Comment by zhumangma** [comment]
gog版本的

**Comment by zhumangma** [comment]
我加了一个汉化的mod，启动器能打开游戏了，就是游戏内的物品介绍界面没了 包括触发事件的那个选择界面也没了
![11](https://github.com/shabbywu/Battle-Brothers-CN/assets/153610351/e256b44d-8415-4c27-a6c1-238fd0bb677a)

**Comment by zhumangma** [comment]
OK 了，是我加的mod的问题 我把原来的汉化补丁删了之后出现的问题 我又重新加回来就行了 
![{27198744-0615-4811-A3FD-2782F2B00F88}](https://github.com/shabbywu/Battle-Brothers-CN/assets/153610351/59fe60c9-2208-4b50-b26f-964fb0f2e8da)

**Comment by shabbywu** [comment]
@zhumangma Mod打包以附件形式上传，这样我有空就可以排查下。看下能不能避免这个情况。

**Comment by zhumangma** [comment]
好的 23067那个文件是后面加的汉化mod 第二张图是我没打汉化补丁之前的mod配置，我把原来的那个zbigmap001给删掉了，后面又加回来就好了。
[mod.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/13656542/mod.zip)

**Comment by zhumangma** [comment]
[mod_hooks_李剑汉化230627集成_with_blackscreen_fixed.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/13656713/mod_hooks_.230627._with_blackscreen_fixed.zip)

**Comment by wll3333** [comment]
GOG启动失败 遇到这个提示要怎么修复？
![微信截图_20231215083220](https://github.com/shabbywu/Battle-Brothers-CN/assets/20547517/9c6b0e68-16fa-4378-94f0-094206855229)

**Comment by shabbywu** [comment]
> GOG启动失败 遇到这个提示要怎么修复？ ![微信截图_20231215083220](https://private-user-images.githubusercontent.com/20547517/290691405-9c6b0e68-16fa-4378-94f0-094206855229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzAyNzUsIm5iZiI6MTcwMzcyOTk3NSwicGF0aCI6Ii8yMDU0NzUxNy8yOTA2OTE0MDUtOWM2YjBlNjgtMTZmYS00Mzc4LTk0ZjAtMDk0MjA2ODU1MjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAyMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNWYwYWE2YWQ2ZjQ3ZjZlMGYxNzBmYjJkZjBmNGZlMmE3NmJkOGEwZDVlNzkyOTY5MTM1NTk3N2NkMjZjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJ9u_7ak0LZsK12-wmIP5Uwjj66nDSzTG3nAUQnX_BM)

你这啥古早操作系统？PowerShell都没有

**Comment by shabbywu** [comment]
终于完全重写启动器了，避免了这些复杂的依赖问题。

https://www.nexusmods.com/battlebrothers/mods/719
