### ISSUE TITLE
大地图城市名字乱码以及加其他mod失效的问题

### ISSUE THREAD

**Issue by EndlessLoops** [shabbywu/Battle-Brothers-CN#124]
1. 如果不用汉化程序自带的启动器，使用默认官方的启动程序的话会出现大地图城市乱码的情况
2. 在使用汉化程序自带的启动器后，不会出现地图城市名称乱码的情况；但是再添加其他功能mod比如zbigmap整合包的mod，会出现使用汉化程序自带的启动器启动后，不能正常进入游戏的情况。卡在开始的白屏界面，然后就退出游戏程序了

**Comment by shabbywu** [comment]
1. 压缩所有 Mod 并以附件形式上传
2. 附件上传你游戏启动时的 log.html（在「我的文档」里）

**Comment by EndlessLoops** [comment]
[log.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/13904899/log.zip)
[mod.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/13904905/mod.zip)

**Comment by shabbywu** [comment]
缺失 mods_registerJS
需要下载 MSU 的前置依赖  https://www.nexusmods.com/battlebrothers/mods/42?tab=files
