### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by shuguang2000** [shabbywu/Battle-Brothers-CN#126]
建议在物品价值后面加上克朗的图片么，就是商店商品前面的那个黄色小点。
![1](https://github.com/shabbywu/Battle-Brothers-CN/assets/92711447/f071f727-f21a-4333-9262-67af9671aeda)

**Comment by shuguang2000** [comment]
> 建议在物品价值后面加上克朗的图片么，就是商店商品前面的那个黄色小点。 ![1](https://private-user-images.githubusercontent.com/92711447/293497368-f071f727-f21a-4333-9262-67af9671aeda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTM3MDIsIm5iZiI6MTcwNDAxMzQwMiwicGF0aCI6Ii85MjcxMTQ0Ny8yOTM0OTczNjgtZjA3MWY3MjctZjIxYS00MzMzLTkyNjItNjdhZjk2NzFhZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5MDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYzk4MTY0MTQxZTZmNTdmZTY3ZTU3ZDk0NGFjOGM0MGQ3YjFjZjY2YzQ2Y2RhOGM4ZWNiYWQ5YzQyYWUxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q4WSuBs_gp4BIhvU3sk1_vhWkNuK2CAJ_SCWmHceAk4)

**Comment by shabbywu** [comment]
有可能是bug.
