### ISSUE TITLE
启动器启动失败

### ISSUE THREAD

**Issue by LCM1999** [shabbywu/Battle-Brothers-CN#128]
Steam版本，今天忘了用启动器，直接steam启动，进游戏后发现乱码，退出后，再用启动器启动，发现无法启动，shell内容如下：
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/52990118/a966e3f3-0512-4c5a-a2b2-c2913ca925aa)
重新使用翻译器执行翻译、更换源执行翻译，再使用启动器启动，均无效

**Comment by LCM1999** [comment]
Active code page: 65001
[*] Loading PE...
[*] Loaded, size: 3325952
[*] Initializing...
[*] Initialized
[*] Running...
Press Enter to continue...:

按enter后命令行关闭，游戏未启动

**Comment by LCM1999** [comment]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/52990118/89a7178b-63b9-45c0-9cd1-2bed8c4c4e58)
一次启动失败后的错误提示

**Comment by shabbywu** [comment]
steam 客户端有正常运行吗
确认是用 steam 版的启动器启动吗？

**Comment by LCM1999** [comment]
重启steam后问题解决，应该是如果先用steam启动游戏才会有这个问题。
