### ISSUE TITLE
执行翻译 错误代码1

### ISSUE THREAD

**Issue by hdx731** [shabbywu/Battle-Brothers-CN#129]
![4OED@ZRW69H_K9M{3I KBVJ](https://github.com/shabbywu/Battle-Brothers-CN/assets/155769950/2adaccb8-27f9-4342-839c-61efe081db2c)

**Comment by shabbywu** [comment]
你的网络环境无法访问部署在腾讯云的服务器，有办法换个网再执行吗

**Comment by hdx731** [comment]
我人在加拿大有什么办法么请问

**Comment by hdx731** [comment]
感谢回复 问题已经通过用手机翻墙回国内 开个人热点的方式解决了 谢谢

**Comment by shabbywu** [comment]
....反向墙，我佛了。
