### ISSUE TITLE
数字摘要不一致

### ISSUE THREAD

**Issue by willxudallas** [shabbywu/Battle-Brothers-CN#145]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/44008280/6e680492-f1d0-4217-8501-992ed1f27f94)

下载的最新release,一开始以为是版本问题，然后把游戏卸载之后又clean install的 （游戏的mod文件和Documents里的save都删了），但是启动器启动时还是显示数字摘要不一致。请问一下应该怎么解决？

**Comment by shabbywu** [comment]
Battle-Brothers-CN 目录里有下载好的文件，应该是 .exe 结尾的。你删一下。

**Comment by willxudallas** [comment]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/44008280/7a276ecc-4f1f-4ec2-9d49-1cf7fe209230)

好的,但是我在Battle-Brothers-CN文件夹里没有找到.exe结尾的文件. 

压缩的文件大小超过25MB的大小限制了不能上传附件,所以我上传到google drive了. 这是link: https://drive.google.com/file/d/1YYsREF7dxCLIpjBN5i8xL-utRaMk0wud/view?usp=sharing

**Comment by shabbywu** [comment]
我的锅. 前段时间修改了网站的后台服务器，然后因为 DNS 缓存问题流量还是流入旧服务器，所以没看出来现在服务挂了。
我修下

**Comment by shabbywu** [comment]
应该可以了，CDN 加速也预热好了。

如果还不行的话，你直接到这2个地址下载启动器放到 Battle-Brothers-CN 目录下就行.
http://battle-brothers-cn.shabbywu.cn/files/bb-launcher-gog.exe
http://battle-brothers-cn.shabbywu.cn/files/bb-launcher-steam.exe

**Comment by willxudallas** [comment]
可以正常启动了,非常感谢!
