### ISSUE TITLE
能不能解答一下两个问题？

### ISSUE THREAD

**Issue by wuxiangjinxing** [shabbywu/Battle-Brothers-CN#15]
1）在有源代码的前提下（.nut）文件，用什么方法生成翻译使用的.po文件？
2）翻译完之后，要如何生成你发布的data文件？

**Comment by shabbywu** [comment]
在搞一个汉化的工具，晚点会发布

**Comment by shabbywu** [comment]
bb-translator 发布了, 如果没其他问题，这个 issue 先关闭了
