### ISSUE TITLE
使用啟動器時出現錯誤

### ISSUE THREAD

**Issue by SeaKaByt** [shabbywu/Battle-Brothers-CN#150]
错误代码: -529697949
 
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/88830273/0528386a-4d77-40e1-8051-68829b494a9e)

错误代码: -1073741819

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/88830273/6fd553e3-88d2-48f8-8ecc-620368164a4f)

**Comment by shabbywu** [comment]
报错大致上是由于初始化 Steam 失败，导致启动失败。

1. 第一个截图看起来是连 Steam 失败，尝试重启 Steam 客户端
2. 缺失 Galaxy.dll 这个报错是因为你是 Steam 的版本，不能用 GOG。（如果硬是要用的话，可以下载 Galaxy.dll 放到 win32 目录，也能运行的，只是这样就连不了 Steam 成就）

**Comment by SeaKaByt** [comment]
> 报错大致上是由于初始化 Steam 失败，导致启动失败。
> 
> 1. 第一个截图看起来是连 Steam 失败，尝试重启 Steam 客户端
> 2. 缺失 Galaxy.dll 这个报错是因为你是 Steam 的版本，不能用 GOG。（如果硬是要用的话，可以下载 Galaxy.dll 放到 win32 目录，也能运行的，只是这样就连不了 Steam 成就）

本來也能正常開啟動器 後來就一直開啟動器就出現這個error 重啟Steam也沒有解決問題

**Comment by shabbywu** [comment]
启动器重写了，重写过程遇到类似这样的问题，我当时是先用 Steam 启动 1 次游戏（因为需要触发 Steam 云的更新同步），之后用启动器启动就正常了。

另外，最新的启动器可以在这里下载 https://www.nexusmods.com/battlebrothers/mods/719
