### ISSUE TITLE
翻译时出现一个错误

### ISSUE THREAD

**Issue by nus1998** [shabbywu/Battle-Brothers-CN#155]
```
desc:expression expected
source:scripts/!mods_preload/!!redirect.nut
line:104
column:9
invalid sourcecode, failed to compile scripts/!mods_preload/!!redirect.nut
```

应该是mod hook(里的!!redirect.nut

另外如果挂载了mod_settlement_prices_tooltip, 会出现警告:
```
warning!!! sourcename != clousure.sourcename ('scripts/!mods_preload/mod_settlement_prices_tooltip.nut' != 'D:\PROGRAMMING\SQUIRREL\dev\settlement_prices_tooltip\mod_settlement_prices_tooltip.nut')
```

编辑: 好像没影响?? 可以进游戏, 需要mod hook的那些mod也正常可用

**Comment by shabbywu** [comment]
”scripts/!mods_preload/!!redirect.nut“ 可忽略，这文件通常来说没有文本。
报这个错有可能是因为我用的 squirrel 版本是 3.2 最新版，Battle Brothers 用的是 3.0.4 老版本。具体是啥原因没具体关注，因为没影响。。


现在翻译文件是根据每个问题提取的文本来编排目录的，所以依赖了 sourcename 这属性。
warning 这种是因为打的 Mod 脚本编译方式不规范，文件所在的实际路径和编译到 .cnut 里的路径不一致，目前以实际路径为准。所以也可以忽略。
