### ISSUE TITLE
steam版执行翻译报错

### ISSUE THREAD

**Issue by fruit368** [shabbywu/Battle-Brothers-CN#163]
执行失败, 错误代码: -1073741515, 窗口将在10秒后关闭
按 Enter 键继续...:

怎么办

**Comment by shabbywu** [comment]
关了离线特权试试，应该就好了。上次把这个功能搞坏了。

**Comment by fruit368** [comment]
> 关了离线特权试试，应该就好了。上次把这个功能搞坏了。

没开离线特权…是要登录才能用吗

**Comment by shabbywu** [comment]
翻译功能需要联网热更脚本，现在启动器除了下载对应版本的启动器，已经不需要联网。

**Comment by shabbywu** [comment]
修复了，是腾讯云偷偷将云函数降配了，导致触发了请求超时...
