### ISSUE TITLE
貌似同时对hook和msu这两个前置有需求的mod会导致启动器启动时闪退。

### ISSUE THREAD

**Issue by dimoolin** [shabbywu/Battle-Brothers-CN#171]
我用二分法筛了一遍我安装的mod，只要是存在同时需要 modding script hooks 和 Modding Standards and Utilities (MSU) 这两个做前置的mod都会导致闪退，删除了就没问题。
![屏幕截图(2)](https://github.com/shabbywu/Battle-Brothers-CN/assets/60121440/3fda938c-1e83-4b90-bd74-3d09d74e7dde)

![屏幕截图(3)](https://github.com/shabbywu/Battle-Brothers-CN/assets/60121440/3140f92f-351a-4bbb-b961-0e3976870062)

**Comment by shabbywu** [comment]
首先很抱歉隔了2周才看issue, 最近在弄另一个项目.
方便提供一下 “同时需要 modding script hooks 和 Modding Standards and Utilities (MSU) 这两个做前置的mod” 吗，因为我基本不用 Mod。

**Comment by dimoolin** [comment]
我只测试了三个，以下
Clever Recruiter
https://www.nexusmods.com/battlebrothers/mods/549
Weapon Maths
https://www.nexusmods.com/battlebrothers/mods/559
Extra Keybinds
https://www.nexusmods.com/battlebrothers/mods/550

**Comment by shabbywu** [comment]
刚刚试了单独安装 Weapon Maths 和 hook 和 msu. 复现不了报错。
https://www.nexusmods.com/battlebrothers/mods/42
https://www.nexusmods.com/battlebrothers/mods/479
https://www.nexusmods.com/battlebrothers/mods/559

如果还方便的话，可以把你稳定报错的 data 目录截图下吗
<img width="621" alt="image" src="https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/34b8e572-2881-4d57-ab5c-f1b3ce96274c">

从你上面提供的截图来看，你应该是用了 N 网那个 vortex mod manager 管理 Mod, 我不是很清楚这里会不会有额外的干扰。

另外我自测时用的是 https://github.com/shabbywu/Battle-Brothers-CN/releases/download/v20231206/bb-translator.exe.zip 这个版本的启动器，没有生成翻译文件。

**Comment by Cheeseberg96** [comment]
应该是你用的一个mod动了UI相关

**Comment by shabbywu** [comment]
启动器重写了，理论上这种报错会有更清晰的错误提示。

https://www.nexusmods.com/battlebrothers/mods/719
