### ISSUE TITLE
一堆麻烦问题期望指教

### ISSUE THREAD

**Issue by Rayforward** [shabbywu/Battle-Brothers-CN#18]
我是一个接触这游戏的新人以及一个有一定经历的游戏汉化者，发现这个游戏有着漫长的国内社群历史（从2017）和奇怪的汉化生态（对比用transfix或者paratranz等中心化合作方式的其他汉化项目），qq群补丁（我没尝试）、奇怪的游侠汉化、别的地方ui文本与本项目不同但其余地方一样的汉化……似乎有很多不同的且都不完善的汉化在存在着？本项目目前拥有的文本处于一种什么状态呢？稍微体验了一下游戏发现确实存在不少可怕的语序问题，在线项目的文本拆分也稍微扩大了一点汉化工作的困难度的样子[
[Will spoil in [color=+[/color] days.

对比
	text = text.replace(/Will spoil in (.*?) days\./, "会在 $1 天后变质腐烂。");
]，总之，关于“这游戏年代这么久了为啥汉化一盘散沙”、“这游戏年代这么久了汉化质量可惜存在遗憾”&“看贴吧还有好多奇怪的QQ群撕逼环节”等诸多疑惑，等待指教，同时，还是要表示对站出来重新把汉化工作带上一个新起点（早该中心化了）的作者你的敬意，敬上！

PS：其实我挺乐意参与汉化修正的，希望能有个qq群或者DC群用于快捷交流

**Comment by Rayforward** [comment]
啊，另外，在体验了一下目前的在线站后感觉其实并不好用……特别是搜索功能，每次得退出到主页才能进行全文件搜索，如果不介意我推荐把项目转移到paratranz.com，这是一个从P社游戏开始逐渐拓展领域的汉化合作站，我蛮有使用历史了，而且我跟站长联系过支持po格式，以下是实例，我未经许可上传了一份po文件供您参考使用体验，希望能纳入考虑：https://paratranz.cn/projects/7020

**Comment by shabbywu** [comment]
- 本项目目前拥有的文本处于一种什么状态
> 文本是(根据 squirrel-lang 的虚拟机语法)从游戏的 .cnut 提取出来的, 是从 1.5.0.14 提取的

- 奇怪的游侠汉化
> 游侠汉化据说是基于很老的游戏版本弄的, 目前最新的游戏版本好像已经用不了了

- qq群补丁
> qq群补丁是用 js 做的汉化, 因为是在前端做的文本替换，在某些场景的汉化质量是会比目前这个版本的内核汉化要好的
> 因为外挂汉化是在游戏文本渲染后再做替换，配合正则使用就可以在一定程度上解决语序的问题
> 然而 qq 群补丁我觉得最严重的问题就是一盘散沙, 压根不知道哪里汉化了，哪里没汉化。所以我才重新研究了这个游戏引擎的机制，将文本全提取出来，这样就算我以后弃坑了，后面有人感兴趣接手也不至于要重新摸索

---
汉化项目是开源的, 本质就是希望可以有人参与共建.
如果有免费的在线项目可以用的话，我当然很乐意转去其他站点啊...毕竟现在这个破站还占了我一台 2C4G 的VPS呢. 都是💰啊

**Comment by shabbywu** [comment]
关于语序问题，我也有在研究怎样解决，例如
- 将语序有问题的文本单独拎出来做成外挂汉化
- 精细化处理，修改游戏脚本的代码直接调整语序


这游戏的实现是真的烦人, 明明 squirrel 提供了字符串模板渲染的功能，偏偏要用字符串拼接的方式来组装文本。

**Comment by Rayforward** [comment]
请务必速速转到paratranz，我十分推荐，站长是活人好交流，也支持po格式的翻译文本（还是我当年折腾kenshi时候有的），我的翻译之魂已经烧起来了！如果你觉得麻烦我也可以代劳，单纯把项目里的po全部传过去即可。还有就是解决发布问题，最好能及时把paratranz上的po更新到git里以提供给bbtranslator下载，这一点上para有提供api，我认为应该能实现[https://paratranz.cn/docs]。此外为了本地测试之便，我推荐给bbtranslator提供一个从本地po进行cunt编译的功能。
总之，诸多我希望的方面，希望能纳入考虑。还有就是更迅速的联系方式，求建设q群或dc群！

**Comment by Rayforward** [comment]
paratranz兼容性还存在一点问题，会把po文件如：
#
msgid ""
msgstr ""

# scripts/ambitions/ambition.nut
msgid "Your Task"
msgstr "任务"

# scripts/ambitions/ambition.nut
msgid "Your Reward"
msgstr "报酬"

# scripts/ambitions/ambition.nut
msgid "Your Renown will increase, which means higher pay for contracts and potentially unlocking new types of contracts."
msgstr "你的声望会提高，这意味着合同的报酬会更高，并有可能解锁新类型的合同。"

里的# scripts/ambitions/ambition.nut键值变成乱码，这是会影响使用的吧？我在和站长联系了

**Comment by shabbywu** [comment]
我也可以抽空把 po 转成 json 格式. 就是写个脚本的事情.

**Comment by shabbywu** [comment]
这周末争取抽空处理下这个吧..社畜工作日太忙了

**Comment by Rayforward** [comment]
明白了，对于一个汉化爱好者而言按照一个很闲的人的预期等您的回复实在太折磨了，现在算是心安了.
我自己没有任何编程基础，今天问了gpt一早上如何实现cnut-nut-po-nut-cunt的流程不得其解，还是得在这对您的技术嗷嗷待哺（如果能公布bbtranslator的源码什么就太感谢了）总之我先把我希望的这个项目需要的优化写在这:
1：迅速的汉化测试，bbtranslator可选本地po/json进行cunt编译以便快速测试汉化效果（从git拉还要经过pr这个需要审核的步骤，不够快捷）
2：优化在线翻译合作项目
3：qq群、DC群

**Comment by shabbywu** [comment]
[bb-translator.exe.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/11428691/bb-translator.exe.zip)

添加了启动参数 `--disable-git`

在 powershell 或者 cmd 执行 `bb-translator.exe --disable-git` 就可以跳过拉取 git

**Comment by Rayforward** [comment]
> [bb-translator.exe.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/11428691/bb-translator.exe.zip)
> 
> 添加了启动参数 `--disable-git`
> 
> 在 powershell 或者 cmd 执行 `bb-translator.exe --disable-git` 就可以跳过拉取 git

测试可用，不过已确定如兄弟的背景描述文本应该是保存在存档里了，不会根据汉化更改而更改，这点可能需要在以后说明

**Comment by DarkSjm** [comment]
这几天手动改了一些文本里面的机翻，我没梯子改在线仓库太慢，需要的话我可以发你邮箱

**Comment by Rayforward** [comment]
> 这几天手动改了一些文本里面的机翻，我没梯子改在线仓库太慢，需要的话我可以发你邮箱

主要是等待作者君把在线项目搞定，这样可以彻底放手开工。我现在也是在本地先改着自用

**Comment by Rayforward** [comment]
周末了！先把我改了一堆的po传上来，weblate好像炸了
链接: https://pan.baidu.com/s/174JTvTfsATQRtzXuGTx2Iw?pwd=1234 提取码: 1234 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v5的分享

**Comment by DarkSjm** [comment]
> 周末了！先把我改了一堆的po传上来，weblate好像炸了 链接: https://pan.baidu.com/s/174JTvTfsATQRtzXuGTx2Iw?pwd=1234 提取码: 1234 复制这段内容后打开百度网盘手机App，操作更方便哦 --来自百度网盘超级会员v5的分享

你改的好像没我改的多，麻烦问下地图上生物名称在哪个PO？？就是鼠标放上去显示的名字，有些没翻，我有点强迫症，比如说北方巨魔和伊芙利特

**Comment by shabbywu** [comment]
先不要往 weblate 推送, 有修改冲突。
我正在迁到 paratranz, 稍等下

**Comment by shabbywu** [comment]
@Rayforward @DarkSjm 两位大佬，我用了上面提到的那个项目做测试，这个项目文件搞得有点乱，我重新建了个项目，我把旧的删掉，没问题把？

新建的在线协同项目 https://paratranz.cn/projects/7032

**Comment by shabbywu** [comment]
花了一周时间重写了 .cnut 的反编译程序, 现在把那些奇怪语序的文案的上下文也提取出来了.

效果大概是这样，应该可以很好的协助人力翻译
<img width="678" alt="image" src="https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/1a1cc9c3-03ce-4f8b-9eef-92da77a87996">

**Comment by shabbywu** [comment]
> > 周末了！先把我改了一堆的po传上来，weblate好像炸了 链接: https://pan.baidu.com/s/174JTvTfsATQRtzXuGTx2Iw?pwd=1234 提取码: 1234 复制这段内容后打开百度网盘手机App，操作更方便哦 --来自百度网盘超级会员v5的分享
> 
> 你改的好像没我改的多，麻烦问下地图上生物名称在哪个PO？？就是鼠标放上去显示的名字，有些没翻，我有点强迫症，比如说北方巨魔和伊芙利特


地图上的实体对象的名称一般在 https://paratranz.cn/projects/7032/settings/files#scripts%2Fentity%2Fworld%2F 这个层级的代码里维护
没记错的话，这游戏地图上的实体名称也是存储在存档里的，所以如果这个对象没被销毁重建，就会一直显示英文 🐶

**Comment by Rayforward** [comment]
感谢你的程序（我完全做不到的地方）付出，已经确定从para下来的json可以用了吗？确定我就可以放心开干了

**Comment by shabbywu** [comment]
> 感谢你的程序（我完全做不到的地方）付出，已经确定从para下来的json可以用了吗？还有json的本地打包回cnut，确定我就可以放心开干了

基于 para 的文本翻译还需要重新弄下，现在只把文本推上去了

**Comment by Rayforward** [comment]
就等着本地适配啦。还有，能用我的po转json吗，改了老多了

**Comment by shabbywu** [comment]
> 就等着本地适配啦。还有，能用我的po转json吗，改了老多了

今天主要抽空看了下 paratranz 发版本的流程, 因为导出归档包是异步的, 所以从 paratranz 实时翻译会比较麻烦, 
我处理完发版本的流程后, 再将网盘的 po 更新的内容同步到现在的 json.
最后再将翻译改成用 json 来处理.

**Comment by Rayforward** [comment]
> > 就等着本地适配啦。还有，能用我的po转json吗，改了老多了
> 
> 今天主要抽空看了下 paratranz 发版本的流程, 因为导出归档包是异步的, 所以从 paratranz 实时翻译会比较麻烦, 我处理完发版本的流程后, 再将网盘的 po 更新的内容同步到现在的 json. 最后再将翻译改成用 json 来处理.

也可以定期从para拉出json打包慢慢放git上？

**Comment by shabbywu** [comment]
在线翻译的协同流程和工具已经发布了 
https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/tools-v0.0.1

**Comment by Rayforward** [comment]
好耶，还剩我的po

**Comment by shabbywu** [comment]
写了个 bug...晚点再更新协同工具

**Comment by shabbywu** [comment]
bug 应该修复了, 协同工具发布了

**Comment by Rayforward** [comment]
试着重新生成压缩包，用了下[sync-from-paratranz-tools-v0.0.3-windows-amd64.zip](https://github.com/shabbywu/Battle-Brothers-CN/releases/download/tools-v0.0.3/sync-from-paratranz-tools-v0.0.3-windows-amd64.zip)的，没有变化？还有我滴po XD

**Comment by shabbywu** [comment]
> 试着重新生成压缩包，用了下[sync-from-paratranz-tools-v0.0.3-windows-amd64.zip](https://github.com/shabbywu/Battle-Brothers-CN/releases/download/tools-v0.0.3/sync-from-paratranz-tools-v0.0.3-windows-amd64.zip)的，没有变化？还有我滴po XD

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/7d69b08c-e583-4dec-adf2-0e59b8d8e979)

我猜你改了这？在 windows 下有问题么，我还没在 win 测试。

**Comment by Rayforward** [comment]
> > 试着重新生成压缩包，用了下[sync-from-paratranz-tools-v0.0.3-windows-amd64.zip](https://github.com/shabbywu/Battle-Brothers-CN/releases/download/tools-v0.0.3/sync-from-paratranz-tools-v0.0.3-windows-amd64.zip)的，没有变化？还有我滴po XD
> 
> ![image](https://user-images.githubusercontent.com/5237578/238657197-7d69b08c-e583-4dec-adf2-0e59b8d8e979.png)
> 
> 我猜你改了这？在 windows 下有问题么，我还没在 win 测试。

对，我改了para的词条，重新生成了压缩包，在win10系统下开或不开提子双击那个exe，好像啥也没发生

**Comment by shabbywu** [comment]
示例: sync-from-paratranz

# 在控制台终端(cmd 或 powershell) 中执行（就和 bb-translator.exe 加 --disable-git 参数一样）
❯ sync-from-paratranz.exe --token ${YOUR-API-TOKEN} --project 7032

不过 sync-from-paratranz 需要在 Battle-Brothers-CN 目录下执行

**Comment by DarkSjm** [comment]
请问下原本的汉化工具失效了嘛？
加了--disable-git参数还是需要更新工具，然后总是更新失败

**Comment by Rayforward** [comment]
运行是运行起来了，但是sync-from-paratranz好像作用是把我本地Battle-Brothers-CN 目录下的nut更新了？没有对git项目做什么的样子，单纯是从paratranz拉文件回来用？

**Comment by shabbywu** [comment]
> 请问下原本的汉化工具失效了嘛？ 加了--disable-git参数还是需要更新工具，然后总是更新失败

可以贴一下错误信息吗？

**Comment by Rayforward** [comment]
> > 请问下原本的汉化工具失效了嘛？ 加了--disable-git参数还是需要更新工具，然后总是更新失败
> 
> 可以贴一下错误信息吗？

bb是汉化仓库状态更新失败: non-fast-forward update，sync-from-paratranz单纯是从para在本地Battle-Brothers-CN造nut？

**Comment by DarkSjm** [comment]
> > > 请问下原本的汉化工具失效了嘛？ 加了--disable-git参数还是需要更新工具，然后总是更新失败
> > 
> > 
> > 可以贴一下错误信息吗？
> 
> bb是汉化仓库状态更新失败: non-fast-forward update，sync-from-paratranz单纯是从para在本地Battle-Brothers-CN造nut？

提示 non-fast-forward update

**Comment by DarkSjm** [comment]
> > 请问下原本的汉化工具失效了嘛？ 加了--disable-git参数还是需要更新工具，然后总是更新失败
> 
> 可以贴一下错误信息吗？

提示 non-fast-forward update

**Comment by shabbywu** [comment]
non-fast-forward update 是因为我精简了这个项目的大小... 所以要删了 Battle-Brothers-CN 重新克隆一次

**Comment by shabbywu** [comment]
更新了支持 ParaTranz 的文本翻译. 可以试试
网盘的文案昨天已经导入了，可以检查下

**Comment by Rayforward** [comment]
> 更新了支持 ParaTranz 的文本翻译. 可以试试 网盘的文案昨天已经导入了，可以检查下

怎么个支持法？是bb.exe能读git上的json了嘛，还有sync-from-paratranz到底是干什么用的？单纯把nut弄到本地？

**Comment by shabbywu** [comment]
> sync-from-paratranz到底是干什么用的？单纯把nut弄到本地
可以这样理解

> 是bb.exe能读git上的json了嘛
对

**Comment by Rayforward** [comment]
> > sync-from-paratranz到底是干什么用的？单纯把nut弄到本地
> > 可以这样理解
> 
> > 是bb.exe能读git上的json了嘛
> > 对

好的谢谢，可以走上正轨了，干杯！

**Comment by Rayforward** [comment]
> > sync-from-paratranz到底是干什么用的？单纯把nut弄到本地
> > 可以这样理解
> 
> > 是bb.exe能读git上的json了嘛
> > 对

啊，但是说回来，这样以来sync-from-paratranz不太符合“使用 sync-from-paratranz 同步最新翻译到 git 仓库”的说法吧……好像对于汉化工作没什么用？
看样子以后工作流程单纯是在para写，等着每日pr合并到github，用bb-translator.exe翻译……
能让bb-translator.exe用上本地同步来的nut吗，及时的那种，方便确认一些任务文本的翻译效果

**Comment by shabbywu** [comment]
这里有2个“本地”需要纠正下名词用法。

1. sync-from-paratranz 是从 para 同步到“本地”，这里的本地是相对于 para 而言的。
这句话换一个表示就是“使用 sync-from-paratranz 同步最新翻译到 git 仓库”。


2. bb-translaotr “本地” 翻译，这里的“本地”是指
bb-translator 克隆的一个本地的 git 仓库，这里的“本地”是 git  local/remotw 仓库之间的说法。


---
纠正文词后，再看看现状:
1. 本地git和远程git对于 para 而言都是“本地”，用 sync-from-paratranz 就是是从 para 下载最新的文本
2. 每日的定时任务是更新远程 git 仓库
3. 你不一定需要等待这个每日同步，你可以用 sync-from-paratranz 更新你的本地 git 仓库，这和2不冲突的

**Comment by Rayforward** [comment]
> 3\. 更新你的本地 git 仓库

哦哦，那我疑惑的是更新本地 git 仓库后怎样让bb-translator用上更新来的nut，生成包含最新改动的zdata_cn.zip呢？

**Comment by shabbywu** [comment]
> > 3. 更新你的本地 git 仓库
> 
> 哦哦，那我疑惑的是更新本地 git 仓库后怎样让bb-translator用上更新来的nut，生成包含最新改动的zdata_cn.zip呢？

1.进入 Battle-Brother-CN 目录执行 sync-from-paratranz 会自动更新 json 目录下的文件，如果你电脑有安装 git, git diff 可以看到变化差异
2. 重新执行 bb-translaotr.exe --disable-git 会自动用本地的文本翻译

**Comment by Rayforward** [comment]
> > > 3. 更新你的本地 git 仓库
> > 
> > 
> > 哦哦，那我疑惑的是更新本地 git 仓库后怎样让bb-translator用上更新来的nut，生成包含最新改动的zdata_cn.zip呢？
> 
> 1.进入 Battle-Brother-CN 目录执行 sync-from-paratranz 会自动更新 json 目录下的文件，如果你电脑有安装 git, git diff 可以看到变化差异 2. 重新执行 bb-translaotr.exe --disable-git 会自动用本地的文本翻译

嗯，我是这么猜想这样的工作流程的，但问题在一我的bb-translaotr.exe --disable-git只认LC_MESSAGES里的po，是不是您这边更新了认json的bb-translaotr.exe忘记发出来了？

**Comment by shabbywu** [comment]
> 

bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先
是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)

**Comment by shabbywu** [comment]
> 

bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先
是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)

**Comment by shabbywu** [comment]
> > > 
> > 
> > 
> > bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> > 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）
> 
> 如果我把LC_MESSAGES文件夹删掉他会说“ValueError: 璺緞閿欒, 璇风‘淇?exit status 1” 如果我把LC_MESSAGESLC_MESSAGES文件夹下po删掉最后汉化会导致很多描述回到英文，感觉像是po优先

喔，想起来了，还有个判断必须要有 LC_MESSAGES

里面的po可以删，LC_MESSAGES文件夹得留着

**Comment by Rayforward** [comment]
> > > > 
> > > 
> > > 
> > > bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> > > 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）
> > 
> > 
> > 如果我把LC_MESSAGES文件夹删掉他会说“ValueError: 璺緞閿欒, 璇风‘淇?exit status 1” 如果我把LC_MESSAGESLC_MESSAGES文件夹下po删掉最后汉化会导致很多描述回到英文，感觉像是po优先
> 
> 喔，想起来了，还有个判断必须要有 LC_MESSAGES
> 
> 里面的po可以删，LC_MESSAGES文件夹得留着

删掉po汉化出来物品、技能描述、过场小tip等等是英文

**Comment by Rayforward** [comment]
> > 
> 
> bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> 
> 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）

呜呜呜，等能用的bb-translator.exe等得好折磨

**Comment by Rayforward** [comment]
> > > > 
> > > 
> > > 
> > > bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> > > 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）
> > 
> > 
> > 如果我把LC_MESSAGES文件夹删掉他会说“ValueError: 璺緞閿欒, 璇风‘淇?exit status 1” 如果我把LC_MESSAGESLC_MESSAGES文件夹下po删掉最后汉化会导致很多描述回到英文，感觉像是po优先
> 
> 喔，想起来了，还有个判断必须要有 LC_MESSAGES
> 
> 里面的po可以删，LC_MESSAGES文件夹得留着

仔细看了下，删掉LC_MESSAGES文件夹里的po后，生成的压缩包里cunt反编译回去后确定汉化不完全，绝大部分文本没有翻译，甚至出现一个nut里翻译前半句、后半句不翻译的情况

**Comment by DarkSjm** [comment]
把CN文件夹po备份以后全删了，用翻译器重新下载一次就解决了啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月20日 12:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shabbywu/Battle-Brothers-CN] 一堆麻烦问题期望指教 (Issue #18) |

bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)

你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）

呜呜呜，等能用的bb-translator.exe等得好折磨

**Comment by DarkSjm** [comment]
> > > 
> > 
> > 
> > bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> > 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）
> 
> 呜呜呜，等能用的bb-translator.exe等得好折磨

你备份修改过的PO以后把Battle-Brother-CN文件夹整个删了，然后用bb-translator重新下载一次再把PO覆盖回去就好了啊

**Comment by Rayforward** [comment]
> > > > 
> > > 
> > > 
> > > bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> > > 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）
> > 
> > 
> > 呜呜呜，等能用的bb-translator.exe等得好折磨
> 
> 你备份修改过的PO以后把Battle-Brother-CN文件夹整个删了，然后用bb-translator重新下载一次再把PO覆盖回去就好了啊

不是，po已经被放弃掉了，现在就是在用json，问题是bb-translator.exe用json翻译会导致翻译很不全

**Comment by DarkSjm** [comment]
> > > > > 
> > > > 
> > > > 
> > > > bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> > > > 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）
> > > 
> > > 
> > > 呜呜呜，等能用的bb-translator.exe等得好折磨
> > 
> > 
> > 你备份修改过的PO以后把Battle-Brother-CN文件夹整个删了，然后用bb-translator重新下载一次再把PO覆盖回去就好了啊
> 
> 不是，po已经被放弃掉了，现在就是在用json，问题是bb-translator.exe用json翻译会导致翻译很不全

我在本地修改PO以后bb-translator.exe正常翻译啊

**Comment by Rayforward** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > bb-translator.exe 的核心代码是热更新，现在是同时只用了 json 和 po，json优先 是不是你本地的 Battle-Brother-CN 仓库没更到最新(如果你没有修改里面的文件都话，删除这个文件夹，bb-translator 会重新克隆一个新仓库)
> > > > > 你可以试试把 po 目录删掉，如果还能正常翻译说明是已经更新了（如果不行的话，那就得发个版本）
> > > > 
> > > > 
> > > > 呜呜呜，等能用的bb-translator.exe等得好折磨
> > > 
> > > 
> > > 你备份修改过的PO以后把Battle-Brother-CN文件夹整个删了，然后用bb-translator重新下载一次再把PO覆盖回去就好了啊
> > 
> > 
> > 不是，po已经被放弃掉了，现在就是在用json，问题是bb-translator.exe用json翻译会导致翻译很不全
> 
> 我在本地修改PO以后bb-translator.exe正常翻译啊

已经不用po了，在线项目格式转换为了json，问题就是用json的翻译问题

**Comment by Rayforward** [comment]
再试了试，好像是读取有问题，每个目录下的nut只读取一个（比如armor和weapon文件夹下的一个nut），别的汉化不生效

**Comment by shabbywu** [comment]
上周没windows环境，没法测试。争取这两天打开游戏确定下是哪里的问题

**Comment by shabbywu** [comment]
> 再试了试，好像是读取有问题，每个目录下的nut只读取一个（比如armor和weapon文件夹下的一个nut），别的汉化不生效


修復了，改成讀 json 后，避免重複讀取文件的邏輯沒調整過來(一起是一个文件夹的文本都放在一个 .po 文件里)

**Comment by Rayforward** [comment]
> \\

还真是，变成\\n了

**Comment by shabbywu** [comment]
sync-from-paratranz 0.0.4 修复了 "\\\\n" 的问题

**Comment by DarkSjm** [comment]
> sync-from-paratranz 0.0.4 修复了 "\\n" 的问题

大佬能不能发布一个只针对本地PO的翻译工具，我都是边玩边改，现在都不敢改了。
我是程序小白，后面弄的json这些不是很懂，而且文本太多找起来不方便
实在麻烦的话请问怎么才能只对本地json生效，很多地方下载的json翻译内容和我一直以来的习惯不一样，有点强迫症

**Comment by shabbywu** [comment]
如果只需要本地翻译的话, 你可以直接用 https://github.com/shabbywu/Battle-Brothers-CN/files/11428691/bb-translator.exe.zip    翻译

如果不会添加启动参数的话，可以把 https://github.com/shabbywu/Battle-Brothers-CN/blob/main/bin/skip_git.bat 这个文件下载到 bb-translator.exe 相同的目录执行


---
还是建议本地调整文本后，到线上也更新下 https://paratranz.cn/projects/7032
po 和 json 文件的映射关系很简单, po 的注释里有写文本原来的文件是哪个文件, 你在 https://paratranz.cn/projects/7032/files 这里的搜索框里直接搜文件名就可以找到对应的 json, 线上修改就可以了
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/463272e7-bac4-458b-afb5-cd351782e00f)


---
本地文本太多找起来不方便的话，建议你安装一个[文本编辑器 vscode](https://code.visualstudio.com/), vscode 可以很方便的搜索文本, 例如
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/169b997a-086c-4bed-b3cf-1425d05d7f02)

**Comment by DarkSjm** [comment]
用以前发布的bb.exe？还是我重新改json文本？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月25日 17:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shabbywu/Battle-Brothers-CN] 一堆麻烦问题期望指教 (Issue #18) |

sync-from-paratranz 0.0.4 修复了 "\n" 的问题

大佬能不能发布一个只针对本地PO的翻译工具，我都是边玩边改，现在都不敢改了。 我是程序小白，后面弄的json这些不是很懂，而且文本太多找起来不方便 实在麻烦的话请问怎么才能只对本地json生效，很多地方下载的json翻译内容和我一直以来的习惯不一样，有点强迫症

你自己改着玩就用原来的bb.exe就行，用：
bb-translator.exe --disable-git
这个命令

现在项目已经在在线协作了https://paratranz.cn/projects/7032

**Comment by DarkSjm** [comment]
感谢，我去试试，文本编辑器我用notepad++和ultraedit，加参数这些都没问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月25日 19:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shabbywu/Battle-Brothers-CN] 一堆麻烦问题期望指教 (Issue #18) |

如果只需要本地翻译的话, 你可以直接用 https://github.com/shabbywu/Battle-Brothers-CN/files/11428691/bb-translator.exe.zip 翻译

如果不会添加启动参数的话，可以把 https://github.com/shabbywu/Battle-Brothers-CN/blob/main/bin/skip_git.bat 这个文件下载到 bb-translator.exe 相同的目录执行

还是建议本地调整文本后，到线上也更新下 https://paratranz.cn/projects/7032
po 和 json 文件的映射关系很简单, po 的注释里有写文本原来的文件是哪个文件, 你在 https://paratranz.cn/projects/7032/files 这里的搜索框里直接搜文件名就可以找到对应的 json, 线上修改就可以了


本地文本太多找起来不方便的话，建议你安装一个文本编辑器 vscode, vscode 可以很方便的搜索文本, 例如

**Comment by DarkSjm** [comment]
另外灵车任务车队名乱码有没有办法解决啊，是不是大地图显示汉字的原因



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月25日 19:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shabbywu/Battle-Brothers-CN] 一堆麻烦问题期望指教 (Issue #18) |

如果只需要本地翻译的话, 你可以直接用 https://github.com/shabbywu/Battle-Brothers-CN/files/11428691/bb-translator.exe.zip 翻译

如果不会添加启动参数的话，可以把 https://github.com/shabbywu/Battle-Brothers-CN/blob/main/bin/skip_git.bat 这个文件下载到 bb-translator.exe 相同的目录执行

还是建议本地调整文本后，到线上也更新下 https://paratranz.cn/projects/7032
po 和 json 文件的映射关系很简单, po 的注释里有写文本原来的文件是哪个文件, 你在 https://paratranz.cn/projects/7032/files 这里的搜索框里直接搜文件名就可以找到对应的 json, 线上修改就可以了


本地文本太多找起来不方便的话，建议你安装一个文本编辑器 vscode, vscode 可以很方便的搜索文本, 例如

**Comment by shabbywu** [comment]
大地图显示不了汉字，接下来就是优化这个大地图乱码的问题

**Comment by DarkSjm** [comment]
一个竞技场锦标赛bug
三连以后对话无响应，拿不到红装
删了zdata_cn可以正常结算

**Comment by shabbywu** [comment]
> 一个竞技场锦标赛bug 三连以后对话无响应，拿不到红装 删了zdata_cn可以正常结算

这个 issue 太长了，重新建了这个问题的单据 https://github.com/shabbywu/Battle-Brothers-CN/issues/46

麻烦贴一下报错信息, 我排查下问题

**Comment by shabbywu** [comment]
我先关闭这个 issue 了
