### ISSUE TITLE
与自动汉化工具冲突的文件

### ISSUE THREAD

**Issue by bdkeystone** [shabbywu/Battle-Brothers-CN#19]
vortex mod配置文件：vortex.deployment.json，
不知为何被作者加密的骑兵mod：zzz_horsemod-507-1-08-1676098727.zip，
还有你的字体文件：zdata_font.zip

**Comment by shabbywu** [comment]
有报错堆栈么.

**Comment by shabbywu** [comment]
是会和 data 目录下的非压缩包冲突，现在解决了(跳过挂载非压缩包类型的文件)
