### ISSUE TITLE
执行翻译失败

### ISSUE THREAD

**Issue by ch624117923** [shabbywu/Battle-Brothers-CN#192]
如图
![QQ图片20240424194129](https://github.com/shabbywu/Battle-Brothers-CN/assets/124593221/afb541c7-fe31-4792-9966-cc51177db706)

**Comment by shabbywu** [comment]
现在的翻译器还是用的在线热更代码，现在触发了3秒接口超时，估计是腾讯云的机器被暗中降配导致的。
我刚调大了超时阈值，应该恢复了。

下个月或者下下个月会出完全离线的版本。

**Comment by ch624117923** [comment]
有了新错误
![QQ图片20240424204655](https://github.com/shabbywu/Battle-Brothers-CN/assets/124593221/2ce63b0f-6ca4-4dfe-8685-13cd3e64bfe1)

**Comment by shabbywu** [comment]
这应该已知的离线特权的bug，关了吧。联网不碍事

**Comment by ch624117923** [comment]
实际上，我在离线特权界面点关闭特权没有反应，如果是要登陆才能关闭的话，我也无法登录
![Uploading QQ图片20240425130900.png…]()

**Comment by ch624117923** [comment]
实际上，我在离线特权界面点关闭特权没有反应，如果是要登陆才能关闭的话，我也无法登录
![QQ图片20240425130900](https://github.com/shabbywu/Battle-Brothers-CN/assets/124593221/73078ace-4a63-418b-bed9-9a0ca3c31e66)

**Comment by octefg** [comment]
登录也无法登录，也无法关闭，就是那个错误代码-107

**Comment by shabbywu** [comment]
> 实际上，我在离线特权界面点关闭特权没有反应，如果是要登陆才能关闭的话，我也无法登录 ![QQ图片20240425130900](https://private-user-images.githubusercontent.com/124593221/325480625-73078ace-4a63-418b-bed9-9a0ca3c31e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzY0MjcsIm5iZiI6MTcxNDEzNjEyNywicGF0aCI6Ii8xMjQ1OTMyMjEvMzI1NDgwNjI1LTczMDc4YWNlLTRhNjMtNDE4Yi1iZWQ5LTlhMGNhM2MzMWU2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxMjU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODBhMzNlYjFkZTkxOWYyZmYwYzA3YTkyZDk2YzU3YjdhZTRhNzY5NGRhOTVlZGIzNzkyZjM1NTU0MmZmNTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QwX_VUy4RrDu5hK8g5ABl2PzeDjGCVIGdDgl4ripqNc)


emmm, 有点低估了墙内的网络状态。看这个状态应该是网络请求堵着，导致 GUI 无响应。
试试到 C:\Users\${你的用户名}\AppData\Roaming\fyne 里删一下缓存，应该可以强制恢复到初始状态。。。然后再试试看吧。

**Comment by shabbywu** [comment]
....我尽快重构完，发布新的翻译器。。。旧的翻译器架构套了几层娃，很难维护

**Comment by octefg** [comment]
fyne 里删除也没用。仿佛是连接不上服务器一样，闪15-6下然后出现错误代码

**Comment by shabbywu** [comment]
@ch624117923 https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v0.7.0-beta.1

昨天赶工写出来的版本，简单测试了能用。如果遇到其他问题继续反馈...

**Comment by octefg** [comment]
打不开，双击没反应，管理员身份也没反应，是不是要删什么

**Comment by shabbywu** [comment]
旧版本已修复，是腾讯云降配导致服务响应超时...先关闭这个issue了
