### ISSUE TITLE
执行翻译失败，错误代码，没有开离线模式

### ISSUE THREAD

**Issue by Knighrt** [shabbywu/Battle-Brothers-CN#193]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets![1q](https://github.com/shabbywu/Battle-Brothers-CN/assets/168021738/a10c7605-a4f7-4614-a6d8-85a1e5f79560)168021738/89b63401-7711-486d-9ea5-c7dc107dc8a

一直是出现这个代码，重装也没法解决，离线特权是关闭状态的

**Comment by Knighrt** [comment]
![1q](https://github.com/shabbywu/Battle-Brothers-CN/assets/168021738/f4a84697-cfc5-4b38-9914-b43f73a253db)

**Comment by octefg** [comment]
我也是

**Comment by shabbywu** [comment]
.....行吧，我尽快重写一个版本。现在为了用起来简单套了几层调用，我现在都不知道问题在哪里了

**Comment by shabbywu** [comment]
@Knighrt @octefg https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v0.7.0-beta.1

**Comment by octefg** [comment]
打不开，双击没反应，管理员身份也没反应。是不是要删什么？

**Comment by octefg** [comment]
只用把exe放根目录，那个source code还用下嘛？完全打不开啊，还是说要重装游戏啊

**Comment by shabbywu** [comment]
换了台电脑，然后发现被杀毒软件拦了...这就难解决了

**Comment by shabbywu** [comment]
重新上传了个未加壳的版本，不会被 windows 识别为病毒。
https://github.com/shabbywu/Battle-Brothers-CN/releases/download/v0.7.0-beta.1/bb_translator.exe.zip

**Comment by shabbywu** [comment]
刚休假回来仔细查了一下，报错是因为腾讯云的云函数偷偷降配，触发了客户端请求的5秒的超时阈值。优化了云函数，现在不会触发超时了。

另外看到 @octefg 说有个群...是啥群

**Comment by shabbywu** [comment]
我这边确认旧版本能重新翻译，先关闭这个 issue 了
