### ISSUE TITLE
有关临时伤残的描述不显示

### ISSUE THREAD

**Issue by FaelGnahz** [shabbywu/Battle-Brothers-CN#199]
目前检查了最近改动内容，没有涉及Injury或skill相关文件，醉酒状态能正常显示，旧存档的临时伤偶尔能显示，新获得的临时伤不能显示。

**Comment by FaelGnahz** [comment]
此外还有一些奇怪的BUG，兽人冲矛墙的结算顺序出现问题，在被矛墙推走之前兽人青年可以打出一次攻击，动画显示也不正常

**Comment by FaelGnahz** [comment]
使用新翻译器生成的https://paratranz.cn/projects/7032/strings?file=986968等构建文本导致相应任务无法打开并导致游戏崩溃

**Comment by shabbywu** [comment]
收到，我修复了旧翻译器的问题了，先别使用新翻译器，我调试好再切换吧。

**Comment by shabbywu** [comment]
排查发现新的翻译器写反了文件挂载逻辑。。。这个bug可能是并发出现的。

**Comment by shabbywu** [comment]
问题理论上已修复，我在自测中.
https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v20240525
