### ISSUE TITLE
几个小的翻译问题

### ISSUE THREAD

**Issue by DarkSjm** [shabbywu/Battle-Brothers-CN#20]
首先感谢大佬这工具，能直接翻译很多MOD，超赞

大佬的汉化里僵尸用的是音译，维德冈格，感觉还是僵尸或者行尸接地气
人皮甲说明每回合回复90点“耐力”感觉应该是“耐久”
这些小问题本来本想自己改，但是翻遍大佬发布的PO文件，找不到对应的字段

**Comment by shabbywu** [comment]
https://github1s.com/shabbywu/Battle-Brothers-CN/blob/HEAD/zh_CN.UTF-8/LC_MESSAGES/scripts_items_armor_legendary.po#L29

github 的搜索有点垃, 可以用 github1s 的搜索，用耐力搜搜到了，的确应该翻译成耐久。

自己改的话可以这样，fock 仓库后在你的仓库修改文本后，可以给本仓库提 Pull requests

**Comment by DarkSjm** [comment]
我是小白不懂怎么给仓库提交文本，我先改本地的试试
怪物名称的PO也找不到啊，物品的找到了
