### ISSUE TITLE
使用新的翻译器 会乱码 变成小方块

### ISSUE THREAD

**Issue by luoluo213** [shabbywu/Battle-Brothers-CN#201]
如题

**Comment by luoluo213** [comment]
![20240506141024_1](https://github.com/shabbywu/Battle-Brothers-CN/assets/169052639/a75ccd10-5254-43e8-8ef5-1d0c0a07b3f9)

**Comment by shabbywu** [comment]
新的翻译器只包含翻译功能，还是要用启动器启动的才会有大地图中文字的功能

**Comment by shabbywu** [comment]
字体需要用启动器，目前最新的启动器预览版已发布在 N网 
https://www.nexusmods.com/battlebrothers/mods/719
