### ISSUE TITLE
【BUG】

### ISSUE THREAD

**Issue by doctr28** [shabbywu/Battle-Brothers-CN#212]
**问题描述**
地图上的各种小队名字出现乱码

**如何复现**
目前打的补丁
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/105599260/507817a4-2f7b-44da-acce-e5920ba09277)

**预期行为**
简要且清晰地描述你预期内这些操作会得到的正确行为

**屏幕截图或录像**
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/105599260/fde36c47-097a-4531-8cae-a9ce7f12a3fe)

**操作系统信息:**
 - OS: [Windows 11]

**Additional context**
如是游戏运行异常，请附带游戏的运行日志(在我的文档/Battle Brothers/log.html)

**Comment by shabbywu** [comment]
用翻译器翻译后，还需要用启动器启动。

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/86c61a1c-05c9-4aed-ae30-c42cb0dd280c)

**Comment by shabbywu** [comment]
看起来是 Mod 的文件名里有不兼容的字符，你试试下载最新的启动器看看能不能解决？
https://www.nexusmods.com/battlebrothers/mods/719

**Comment by doctr28** [comment]
虽然不知道为什么但是今天重装一下游戏+重复一下上述过程就好了
