### ISSUE TITLE
【BUG】安装汉化后，所有的中文都是方块（口）

### ISSUE THREAD

**Issue by SilverCrux** [shabbywu/Battle-Brothers-CN#214]
**问题描述**
安装汉化后，所有的中文都是方块（口）

**如何复现**
复现问题的步骤:
1.使用翻译器 更新翻译项目+ 翻译文本
2. 路径没有中文

**屏幕截图或录像**
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/11873980/65618330-27ad-40e5-ab62-a945dab90cae)

**操作系统信息:**
    Win10 + steam版本游戏

**Comment by shabbywu** [comment]
https://www.nexusmods.com/battlebrothers/mods/719

汉化后需要用启动器启动才能正常显示中文。

**Comment by SilverCrux** [comment]
解决了，非常感谢
