### ISSUE TITLE
【BUG】两种卡死场景

### ISSUE THREAD

**Issue by springlie** [shabbywu/Battle-Brothers-CN#232]
**问题描述**
1.5.0.15 + 官方全DLC + bb-trans1.1.0_preview + bb-launcher-stream-1.0.0_preview3目前发现两种卡死：

1、接到第一个卷轴任务剿灭野人后回城领赏界面，点击“受之无愧” 卡死，读档可重现。
2、到了一个陌生城市，打不开进城画面。背景变暗但前景不出现进不了城，按 ESC 可回到大地图。只要进城即可重现。

**Comment by shabbywu** [comment]
方便上传一下 log.html 吗？crash在日志里肯定有报错，看日志定位最快。

**Comment by springlie** [comment]
> 方便上传一下 log.html 吗？crash在日志里肯定有报错，看日志定位最快。

没有找到log.html，需要的话麻烦告诉一下相对目录。

**Comment by springlie** [comment]
> 方便上传一下 log.html 吗？crash在日志里肯定有报错，看日志定位最快。

当时进程没有crash，只是假死。另外，怀疑是使用了某汉化版本再叠加本补丁造成的，完全卸载后重新使用原英文版+本补丁，问题消失。

**Comment by shabbywu** [comment]
> > 方便上传一下 log.html 吗？crash在日志里肯定有报错，看日志定位最快。
> 
> 没有找到log.html，需要的话麻烦告诉一下相对目录。

我的文档/Battle Brothers/log.html

**Comment by springlie** [comment]
> > > 方便上传一下 log.html 吗？crash在日志里肯定有报错，看日志定位最快。
> > 
> > 
> > 没有找到log.html，需要的话麻烦告诉一下相对目录。
> 
> 我的文档/Battle Brothers/log.html

已经被我新安装的游戏版本覆盖了，没有任何有用信息。我先close掉，如果有问题再开。盲猜大概率是由于某个汉化污染导致的。

**Comment by shabbywu** [comment]
有可能是之前实现的自定义 Mod 加载顺序导致的 bug. 或者是加了新的 Mod 后没有重新生成翻译文件。

刚构建了个版本禁用了自定义 Mod 加载顺序, 1.0.0_preview4
