### ISSUE TITLE
是否跟msu无法兼容？

### ISSUE THREAD

**Issue by Seafoodsz** [shabbywu/Battle-Brothers-CN#234]
有一些mod需要装modern hook和msu，好像放一起时用汉化的启动就会无法启动。。不知道为什么

**Comment by Seafoodsz** [comment]
有几次能进去，但已经是显示方格块，有个msu option这样的英文能看到，其他中文的就全都是方块了

**Comment by shabbywu** [comment]
有可能是之前写的自定义 Mod 挂载顺序的功能有 bug，刚构建了个版本停了这个特性。
https://www.nexusmods.com/battlebrothers/mods/719?tab=files

v1.0.0-preview.4

**Comment by Seafoodsz** [comment]
大赞！

**Comment by Seafoodsz** [comment]
测试了下，还是会闪退 进不了游戏

**Comment by CNwansui2026** [comment]
可能是和modern hook不兼容

**Comment by shabbywu** [comment]
> 测试了下，还是会闪退 进不了游戏

闪退的话，去 「我的文档/Battle Brothers/log.html 」能找到日志文件，里面会有报错信息。（闪退之后马上去看这文件，不然重启游戏会覆盖）

如果日志里有红色的 Error 内容，把这个 log.html 上传上来我看下是哪里冲突导致的。

**Comment by Seafoodsz** [comment]
[log.zip](https://github.com/user-attachments/files/16286879/log.zip)
之前忘了继续弄，看看这个能不能行 麻烦大大了

**Comment by Seafoodsz** [comment]
[log2.zip](https://github.com/user-attachments/files/16286925/log2.zip)
之前的log模拟的不太对，少了hook，这个重新试了下

**Comment by FaelGnahz** [comment]
可以把生成的zdata_cn.zip命名为data_cn.zip来改变加载顺序，以牺牲一部分汉化内容为代价强行兼容，更新翻译时需要改回原名或删除后重新翻译。
1.1.0和旧hook倒是有没解决的兼容问题，伤口详情悬停不显示。

**Comment by shabbywu** [comment]
昨天查了下这个问题，新版的 MSU 改了游戏原来的 fonts.css 逻辑，会导致使用新版 MSU 时字体是方块字。

着急用的话可以直接改 MSU 的样式配置，把字体改回来就能正常展示汉字(有一定门槛)

**Comment by CNwansui2026** [comment]
火手大佬已经做了有字体补丁的MSU
&nbsp;


蓝白的
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月24日(星期三) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shabbywu/Battle-Brothers-CN] 是否跟msu无法兼容？ (Issue #234)














 
昨天查了下这个问题，新版的 MSU 改了游戏原来的 fonts.css 逻辑，会导致使用新版 MSU 时汉字全部变成方块。
 
着急用的话可以直接改 MSU 的样式配置，把字体改回来就能正常展示汉字(有一定门槛)

**Comment by shabbywu** [comment]
[启动器](https://www.nexusmods.com/battlebrothers/mods/719) 已发布 1.0.0 适配 MSU 

另外如果还遇到这个问题，可以用查这问题时开发的 [UI inspector](https://www.nexusmods.com/battlebrothers/mods/744) 来排查
