### ISSUE TITLE
執行翻譯失敗

### ISSUE THREAD

**Issue by alan416007** [shabbywu/Battle-Brothers-CN#243]
系統+遊戲來源 Win10+steam
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/175189511/4c13f492-ed9b-43de-9552-76b076a8ffcf)

**Comment by shabbywu** [comment]
看起来是版本太老，这个版本依赖腾讯云的云函数。由于中国大陆的法规要求，腾讯云云函数功能失效了。
试试用最新重构后的翻译器。
https://github.com/shabbywu/bb-translator/releases/tag/v1.1.0

**Comment by alan416007** [comment]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/175189511/13751f49-b92b-4ae1-be9d-87b40a423e53)
雙擊左鍵打不開

**Comment by alan416007** [comment]
已使用相容性+系統管理員執行，一樣無效

**Comment by shabbywu** [comment]
目前我手上没有 win10 的测试环境，我需要搭建个环境看下具体原因。

**Comment by alan416007** [comment]
了解

**Comment by alan416007** [comment]
了解

**Comment by shabbywu** [comment]
搭建了个 win10 虚拟机，的确如反馈一样无法打开，我排查下。

**Comment by alan416007** [comment]
感謝大佬

**Comment by shabbywu** [comment]
新装的虚拟机安装 VC_redist.x86 后就能打开，你试试这个版本，理论上打开失败能在终端看到报错信息。

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/256c1350-a82c-4f33-82a2-1af867c01194)

**Comment by alan416007** [comment]
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/175189511/26222298-b67b-418d-8fda-15a133f7c381)
現在會跳視窗了，但是大概不到3秒就閃退了

**Comment by alan416007** [comment]
用 Windows PowerShell 開是這樣
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/175189511/a1598334-949c-46fa-aef9-31732cafd9db)

**Comment by shabbywu** [comment]
> ![image](https://private-user-images.githubusercontent.com/175189511/347782090-26222298-b67b-418d-8fda-15a133f7c381.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTYwNDAsIm5iZiI6MTcyMDY5NTc0MCwicGF0aCI6Ii8xNzUxODk1MTEvMzQ3NzgyMDkwLTI2MjIyMjk4LWI2N2ItNDE4ZC04ZmRhLTE1YTEzM2Y3YzM4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMTAyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGJkODZiMzdiMjY3YWZkYTE3MmMwMTFlNTU5ZjZlOWNlMzc0MzE1ZTBlNjhhMGMxOGRiM2E2MGViYmQ5Mzg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EWT80CW0htdPPI-L5WePIkbMK6dme-BSpxtdAP6O3Qs) 現在會跳視窗了，但是大概不到3秒就閃退了

感谢，这个报错信息有用。截图里有个人信息，建议打码重新上传图片。

**Comment by alan416007** [comment]
了解
![347782090-26222298-b67b-418d-8fda-15a133f7c381](https://github.com/shabbywu/Battle-Brothers-CN/assets/175189511/3e031ff3-ec50-4678-8e3a-7aaab9087fe5)

**Comment by shabbywu** [comment]
应该是解压字体文件时不知道什么原因出错了，可以看看这个目录存在吗，里面的内容是否和我截图里的一致。
`C:\Users\{你的用户名}\AppData\Roaming\bb-translator`

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/83b9a402-4bd3-40e0-b2ec-8c35388c8c57)

如果不一致，先删了这个目录，重新启动会自动创建。

**Comment by alan416007** [comment]
一樣

**Comment by alan416007** [comment]
了解了

**Comment by shabbywu** [comment]
试了下不好兼容，新构建的版本能打开但使用不了。。

现在还有个最终方案。

1. 菜单栏搜索 lang 
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/4b2453f7-61a2-4b11-bcda-f5607ccf76eb)

2. 打开管理语言设置
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/7660fc01-b990-4e1a-806b-04d614dc0cf1)

3. 勾选使用 utf-8 编码
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/1b74a3cf-e3eb-43ae-b1b3-c8b7d49016ec)

设置后会需要重启，重启操作系统就默认使用 utf-8 编码。这时候打开就没问题了。

**Comment by shabbywu** [comment]
想到另外的解决方案了，测试了能用，等我用流水线构建好就发布个版本。

**Comment by shabbywu** [comment]
更新 https://github.com/shabbywu/bb-translator/releases/tag/v1.1.2

**Comment by alan416007** [comment]
可以啟動了，感謝
![image](https://github.com/user-attachments/assets/54d726e8-c949-4873-89d3-3dfd50109660)

**Comment by alan416007** [comment]
話說大地圖的地名都是亂碼正常嗎?
![擷取](https://github.com/user-attachments/assets/c76f0d43-e862-4202-9c3c-41e11be69e6e)

**Comment by alan416007** [comment]
以下字體錯位
![0001](https://github.com/user-attachments/assets/6789381e-438d-4838-a782-c012f126acbf)
![0002](https://github.com/user-attachments/assets/b4927a31-fc7f-4d02-89cd-dfa2e3aeb0e4)
![0003](https://github.com/user-attachments/assets/6e8bdad6-41ca-4c08-96be-67d9853905fb)
![0004](https://github.com/user-attachments/assets/d6cc0ff2-fdcd-47c8-8f53-3a3d9264c76e)
![0005](https://github.com/user-attachments/assets/31943adb-c6d3-4bb5-8d21-fd1f72c5611f)

**Comment by alan416007** [comment]
沒事了，我找到方法了
https://www.nexusmods.com/battlebrothers/mods/719?tab=description

![584](https://github.com/user-attachments/assets/0f4af215-6442-4f6c-8fb1-1520b5a033ae)
![589](https://github.com/user-attachments/assets/45471cba-feaf-4850-b81a-daf01eb84f14)

真的很感謝您
