### ISSUE TITLE
【BUG】字体乱码？

### ISSUE THREAD

**Issue by MrDengML** [shabbywu/Battle-Brothers-CN#244]
使用[v1.1.0](https://github.com/shabbywu/bb-translator/releases/tag/v1.1.0)的版本，在win10 的环境下，执行翻译，data目录下也生成了zdata_cn.zip。但是从steam进游戏显示成了这样。
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/54477515/f9465c20-75bb-4085-8b21-6461ca424aa2)

是我的操作有什么不对么

**Comment by shabbywu** [comment]
https://www.nexusmods.com/battlebrothers/mods/719

需要用启动器启动。
