### ISSUE TITLE
大地图上城镇名 地区名乱码

### ISSUE THREAD

**Issue by luke2122** [shabbywu/Battle-Brothers-CN#247]
**问题描述**
简要且清晰地描述问题

用了新版本架构汉化工具后就出现大地图大地图上城镇名 地区名乱码 如图所示，
之前旧版的汉化启动器没有这个问题

**屏幕截图或录像**
![image](https://github.com/user-attachments/assets/2d724a47-303e-48ae-98c1-f8b46a44ab4e)

**操作系统信息:**
Windows 11

**Comment by FaelGnahz** [comment]
使用新版本启动器启动
https://www.nexusmods.com/battlebrothers/mods/719
