### ISSUE TITLE
【BUG】文本显示不全，且有文字重叠

### ISSUE THREAD

**Issue by Unman-Drone** [shabbywu/Battle-Brothers-CN#251]
**问题描述**
使用翻译器进行翻译，并使用启动器进入游戏后。发现游戏内的字体偏向显示框右侧，并且文本显示不全，文字也有很多是重叠的。

**如何复现**
复现问题的步骤:
1. 安装GOG版本的BattleBrothers-1.5.0.15。
2. 在游戏目录中的data文件夹内放入MSU、hooks等mod的压缩文件。
3. 将bb-translator-v1.0.0解压至游戏根目录中运行，并翻译文本。
4. 将bb-launcher-gog解压至游戏根目录中运行。
5. See error

**预期行为**
可能替换字体能够解决这个问题？但我不知道该如何操作。

**屏幕截图或录像**
<img width="200" alt="20240717181920" src="https://github.com/user-attachments/assets/5c3ec134-e639-45f3-882d-70ffa0f37d61">
<img width="360" alt="20240717181924" src="https://github.com/user-attachments/assets/eb3c8259-a993-47a7-ab66-e0eef2a3dd2a">
<img width="103" alt="20240717181926" src="https://github.com/user-attachments/assets/11d8cf75-6064-4ed5-8fd1-f4444d424dd4">

**操作系统信息:**
 - OS: [e.g. Windows 11]

**Additional context**
游戏可以正常运行。

**Comment by alan416007** [comment]
試試看這個
https://www.nexusmods.com/battlebrothers/mods/719?tab=description
![image](https://github.com/user-attachments/assets/928972a2-a40e-4936-a14c-b65c18cf1db5)

**Comment by alan416007** [comment]
有 steam版 跟 本地版 
![image](https://github.com/user-attachments/assets/4881e21f-8d87-4a53-9d0e-b0e6414106af)
放在自己的遊戲目錄下
![image](https://github.com/user-attachments/assets/8355947f-944c-4f5d-8b8c-b7ba7f4294b6)

我的是那個 bb-launcher-steam
點及兩下應該就可以啟動了

**Comment by Unman-Drone** [comment]
> 試試看這個 https://www.nexusmods.com/battlebrothers/mods/719?tab=description ![图像](https://private-user-images.githubusercontent.com/175189511/349733395-928972a2-a40e-4936-a14c-b65c18cf1db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTEyMTUsIm5iZiI6MTcyMTMxMDkxNSwicGF0aCI6Ii8xNzUxODk1MTEvMzQ5NzMzMzk1LTkyODk3MmEyLWE0MGUtNDkzNi1hMTRjLWI2NWMxOGNmMWRiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMzU1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzQ2NzExNjNhMmUwYjM0NjE1MjdhNmM2N2M1Zjk2Yjk2YjU5NjJhMTVkOWU0ZjlmN2QxMDlkZDFiZWExYTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EaeFGEbRb5Z2BcZaAnOWE80iHeSVK-Eo18QRXZ9RslM)

感谢解答，但我就是使用的对应版本的bb-launcher运行的游戏。还有游戏中的部分文本会上下错位，而且我在游玩过程中发现游戏并不能正常运行，接受猎杀野兽的任务会使游戏UI消失，并损坏存档。

**Comment by shabbywu** [comment]
https://github.com/shabbywu/bb-translator/releases

1.0 版本有bug会导致野兽任务无法正常做，在 1.1 版本修复了，最新的是1.1.2
---
错位这个暂时没有头绪，我这边复现不到。

**Comment by FaelGnahz** [comment]
文本错位是MSU的问题，尝试修复过了，可以使用：
https://pan.baidu.com/s/1ijby1P-2G-zbjDr89uujMw?pwd=rz7n
可以跟MSU原本的文件对比看看

**Comment by Unman-Drone** [comment]
> 文本错位是MSU的问题，尝试修复过了，可以使用： https://pan.baidu.com/s/1ijby1P-2G-zbjDr89uujMw?pwd=rz7n 可以跟MSU原本的文件对比看看

非常感谢
