### ISSUE TITLE
【BUG】新版启动器F键被占用，功能为开闭战斗中的战争迷雾

### ISSUE THREAD

**Issue by FaelGnahz** [shabbywu/Battle-Brothers-CN#258]
**问题描述**
新版启动器（1.0.0）F键被占用，功能变为开闭战斗中的战争迷雾

**如何复现**
复现问题的步骤:
随便开一场战斗按F就行了

**预期行为**
结束当前角色回合

**操作系统信息:**
 - OS: [Win10 22H2]

总不能是故意的但是没写出来吧

**Comment by shabbywu** [comment]
好有趣的bug...然而我印象中没弄过这样的特性

**Comment by shabbywu** [comment]
hhhh，我把游戏的 devmode 开了

**Comment by shabbywu** [comment]
翻了下代码，是把 devmode 开了导致的。
![image](https://github.com/user-attachments/assets/7784ffdd-f525-4308-829c-fef535e69aa6)

**Comment by shabbywu** [comment]
=/= 只好把 isDevmode 方法给覆盖了，让他永远返回 false; 

属实没想到打开 remote debugger 之后 isDevmode 也会返回 true;(不得不说这个又很合理)

![image](https://github.com/user-attachments/assets/2c815ea9-e257-4ada-b3fd-0302a3b65b0f)

**Comment by shabbywu** [comment]
https://www.nexusmods.com/battlebrothers/mods/719?tab=files

**Comment by FaelGnahz** [comment]
已经能看到了，确实合理又挺怪的
