### ISSUE TITLE
点击任务后，城镇界面消失

### ISSUE THREAD

**Issue by huanhuenkkk** [shabbywu/Battle-Brothers-CN#261]
出现该问题时，第一次点击任务图标会失败，而第二次点击城镇页面则会消失。
此时会出现二种情况，第1，卡出游戏界面并出现图1图2，并关闭游戏。
第2，游戏正常，并可以关闭消失的城镇界面，但其他城镇同样无法打开。
**如何复现**
不知道，有时第一天就会。
**预期行为**
出现第2种情况时，可通过读取本存档恢复游玩。
出现第1种情况时，该存档直接损坏。并且无法进入，并会跳出图三
**屏幕截图或录像**
![adb36972d00c0b055c7bc34945873cbe](https://github.com/user-attachments/assets/73b66e75-7aa9-4dc7-861d-78e365ade25f)
![8d8e880c7cb194ca18e3e5b64864ed41](https://github.com/user-attachments/assets/4c5a721a-7706-4e6f-8998-1986f378f2fb)
![b77a2805ac2431e1911610387502da11](https://github.com/user-attachments/assets/2d43cb0c-381b-4f1f-a64f-57d4db6e2180)

**操作系统信息:**
 Windows 11

**Additional context**
如是游戏运行异常，请附带游戏的运行日志(在我的文档/Battle Brothers/log.html)
没找到相应文件，对计算机不了解

**Comment by shabbywu** [comment]
https://www.nexusmods.com/battlebrothers/mods/647
