### ISSUE TITLE
【BUG？】翻译完毕后字符变成了方块

### ISSUE THREAD

**Issue by gy0851** [shabbywu/Battle-Brothers-CN#294]
汉化完毕后进入游戏全是方块，汉化过程中没有提示错误，更新翻译是正常的，执行翻译时也提示成功。
<img width="444" alt="111" src="https://github.com/user-attachments/assets/ec41c420-4759-4f06-8205-853853e9bccf">

**Comment by shabbywu** [comment]
翻译文本后需要再下载[启动器](https://www.nexusmods.com/battlebrothers/mods/719)才能运行

**Comment by gy0851** [comment]
感谢

> 翻译文本后需要再下载[启动器](https://www.nexusmods.com/battlebrothers/mods/719)才能运行

感谢！
