### ISSUE TITLE
【BUG】数字摘要不一致

### ISSUE THREAD

**Issue by tu2id4n** [shabbywu/Battle-Brothers-CN#296]
**问题描述**
下载启动器失败，显示数字摘要不一致

**如何复现**
复现问题的步骤:
1.更新翻译
2. 执行翻译
3. 点击steam启动器

**预期行为**
打开游戏

**屏幕截图或录像**
![image](https://github.com/user-attachments/assets/5806af6f-9608-41d2-acfd-427fcffe22be)

**操作系统信息:**
 - OS: [e.g. Windows 11]

**Additional context**
如是游戏运行异常，请附带游戏的运行日志(在我的文档/Battle Brothers/log.html)

**Comment by shabbywu** [comment]
。。。给个图看看行不行

**Comment by tu2id4n** [comment]
> 。。。给个图看看行不行

贴图了，我没有使用任何mod

**Comment by shabbywu** [comment]
直接到这里下 https://www.nexusmods.com/battlebrothers/mods/719 最新的启动器。

你现在用的翻译器也是旧版的，也可以更新到最新的 https://www.nexusmods.com/battlebrothers/mods/647

**Comment by shabbywu** [comment]
这个版本太老，我只记得这个报错是从服务器上下载的启动器和代码里写死的摘要对不上。服务器上的旧启动器我没更新，所以出现这个问题有可能是下载时出现了网络抖动，但是我忘记怎样删已下载的启动器了。

**Comment by tu2id4n** [comment]
> 直接到这里下 https://www.nexusmods.com/battlebrothers/mods/719 最新的启动器。
> 
> 你现在用的翻译器也是旧版的，也可以更新到最新的 https://www.nexusmods.com/battlebrothers/mods/647

没问题了，感谢大佬
