### ISSUE TITLE
【BUG】data文件夹带有对包含snippet_with_func的文件做修改了的mod时会卡住翻译器

### ISSUE THREAD

**Issue by FaelGnahz** [shabbywu/Battle-Brothers-CN#297]
**问题描述**
data文件夹带有对包含snippet_with_func的文件做修改了的mod时会卡住翻译器UI

**如何复现**
复现问题的步骤:
1. 示例文件：https://tieba.baidu.com/p/8520463612二楼网盘链接中的zzz_mod_轻量火手(内有说明)_v22.4.zip
（仅注意到UI停止，未测试是否对生成的汉化文本产生了影响，该mod需要hook前置）

**屏幕截图或录像**
![QQ图片20241006160011](https://github.com/user-attachments/assets/64523065-9573-4387-a2c4-c9963d19f866)
![QQ图片20241006160019](https://github.com/user-attachments/assets/adf7f0be-5aa6-4c9c-853c-269691e31e5c)

**操作系统信息:**
 - Windows 10 22H2

**Comment by shabbywu** [comment]
我看代码里写的是 try-catch，catch 到打印异常后继续执行。

**Comment by shabbywu** [comment]
https://github.com/shabbywu/bb-translator/releases/tag/v1.1.5
