### ISSUE TITLE
发现一个新bug 抵御亡灵事件 弹出来的事件框 直接把全部可能显示的随机文本全显示出来了 长长的一大串

### ISSUE THREAD

**Issue by blackbbq11** [shabbywu/Battle-Brothers-CN#300]
**问题描述**
发现一个新bug 抵御亡灵事件 弹出来的事件框 直接把全部可能显示的随机文本全显示出来了 长长的一大串

**如何复现**
复现问题的步骤:
1. 游戏80天做抵御亡灵事件

**屏幕截图或录像**
![QQ20241013-055637](https://github.com/user-attachments/assets/9945d3ac-c68a-4f93-ade2-fc59094d4558)
![QQ20241013-055655](https://github.com/user-attachments/assets/0b5dfe1d-bdfa-442a-9109-01746a4f5bd9)

**操作系统信息:**
 - OS: [e.g. Windows 11]

**Comment by shabbywu** [comment]
嗯嗯. 已调整。早上自动触发同步后会合并修复。

**Comment by blackbbq11** [comment]
> 嗯嗯。 调整。早上自动触发同步已会合并修复。

大佬 发现去解救绿皮俘虏囚犯事件也有这个BUG 把能显示的文本全显示了 麻烦大佬修复
