### ISSUE TITLE
存在漏翻译

### ISSUE THREAD

**Issue by Rayforward** [shabbywu/Battle-Brothers-CN#35]
发现剧情战霍夫特逃的时候有has retreated from battle，一搜script发现在ai_retreat_always.cnut里，位置是scripts\ai\tactical\behaviors，这个位置的所有nut都没有纳入汉化项目，但是能确定有不止一处可以汉化的词条

**Comment by shabbywu** [comment]
因为在提取文本时 scripts/ai 目录被我直接过滤掉了, 晚点我移除这个过滤看下有啥新文本在里面

**Comment by shabbywu** [comment]
处理了

**Comment by Rayforward** [comment]
我建立好了\ai\tactical\behaviors，同步好到本地，好像bb.exe在翻译时还是跳过了\ai目录

**Comment by shabbywu** [comment]
处理了

**Comment by Rayforward** [comment]
scripts\config\string.nut有两处文本还可以提取出来：

gt.Const.Strings.BodyPartName <- [
	"body",
	"head"
];

这个在战斗中显示xx的head被击中多少伤害

6处引用（actor.nut、lindwurm_tail.nut）：
this.Tactical.EventLog.logEx(this.Const.UI.getColorizedEntityName(this) + "\'s " + this.Const.Strings.BodyPartName[_hitInfo.BodyPart] + " is hit for [b]" + this.Math.floor(damage) + "[/b] damage and suffers " + injury.getNameOnly() + "!");
