### ISSUE TITLE
字体讨论

### ISSUE THREAD

**Issue by Rayforward** [shabbywu/Battle-Brothers-CN#39]
目前用的是LEXUS粗简黑，美观方面是没有问题的，就是不支持很多字比如祂，要不要考虑换成支持范围更广(免得汉化着汉化着丢字都不知道)，免费开源的思源黑体粗？

**Comment by Rayforward** [comment]
[zdata_font.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/11572780/zdata_font.zip)
适配真是有够难的，换了好几家ttf不是字体不全就是直接显示成方块，最后华为的还能用

**Comment by shabbywu** [comment]
https://github.com/ecomfe/fonteditor/blob/master/README.zh-CN.md

理论上可以自己搞个

**Comment by Rayforward** [comment]
> https://github.com/ecomfe/fonteditor/blob/master/README.zh-CN.md
> 
> 理论上可以自己搞个

先换成我这个吧，字符范围广些

**Comment by yk446695192** [comment]
为何我用exe汉化后,世界城镇名字乱符显示,是哪里没操作对么

**Comment by shabbywu** [comment]
现在已支持自定义字体（虽然因为没界面有点难自定义）
