### ISSUE TITLE
翻译结束后提示status=1

### ISSUE THREAD

**Issue by gy0851** [shabbywu/Battle-Brothers-CN#45]
翻译完毕后提示status=1，但小框上方提示error，用cli执行到最后会提示
ValueError: no valiable translations for __main__

At:
  <string>(443): BO
  <string>(450): AL
  <string>(460): BP
  <string>(472): BP
  <string>(472): BP
  <string>(511): BQ
  <string>(501): BQ
  <string>(501): BQ
  <string>(501): BQ
  <string>(534): main
  <string>(9): <module>

exit status 1

这个状态正常吗？

**Comment by Rayforward** [comment]
我一个个版本用过来都没有出现这种情况

**Comment by Rayforward** [comment]
你急也许可以先试试旧版本的bbtranslator.exe

**Comment by shabbywu** [comment]
大概知道是哪里的问题，我修复下

**Comment by shabbywu** [comment]
修复了, 你应该是将上一个版本的翻译文件重命名了？如果是的话，需要先删除旧的翻译文件，避免有其他问题。

**Comment by gy0851** [comment]
搞定了，确实是旧文件的问题，删掉重下就OK拉。

> 修复了, 你应该是将上一个版本的翻译文件重命名了？如果是的话，需要先删除旧的翻译文件，避免有其他问题。 重新启动即可，实时更新的
