### ISSUE TITLE
DarkSjm 反馈 Bug

### ISSUE THREAD

**Issue by shabbywu** [shabbywu/Battle-Brothers-CN#46]
一个竞技场锦标赛bug
三连以后对话无响应，拿不到红装
删了zdata_cn可以正常结算

@DarkSjm 

在这里补充下内容? log.html 里应该有报错

**Comment by DarkSjm** [comment]
https://www.nexusmods.com/battlebrothers/mods/110?tab=files
这个MOD好像不能翻译

**Comment by shabbywu** [comment]
目前翻译的文本不包括 Mod, 不过有计划开始处理 Mod. 可以先列一下你用的 Mod 列表作为参考.

**Comment by DarkSjm** [comment]
又打了一场锦标赛
这个报错，我存了个档，英文打了一遍，汉化打了一遍
英文每场结束跳角斗场数，自动进下一场
打了汉化要手动点竞技场进入下一场，最后一场打完对话没响应，只能放弃
17:08:52Resource
Unloading: music/victory_01.ogg
17:08:52Script Error
comparison between 'bool' and '0'

**Comment by shabbywu** [comment]
https://paratranz.cn/projects/7032/strings?file=918428&anchor=293407868

最近重新 review 整体的翻译进度，找到竞技场锦标赛的文件看了下，以前这个词条被误翻译了，会有问题。这个bug可能就是这导致的。
已经屏蔽了这个问题词条，所以就先 close 了

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/f277000c-60d1-445e-ba5f-1c325af13973)

**Comment by shabbywu** [comment]
再查了下，原来是另一个地方的问题。
<img width="1112" alt="image" src="https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/4f4ce457-c452-4f28-852b-a4e8e5636ac6">
