### ISSUE TITLE
漏提取词条整合

### ISSUE THREAD

**Issue by Rayforward** [shabbywu/Battle-Brothers-CN#49]
scripts/contracts/contracts/investigate_cemetery_contract
line 346 Title = "Approaching...",
Approaching...

**Comment by Rayforward** [comment]
scripts/config/strings.json
line 360 		Cart = "Caravan Cart",
好像因为同文件有头衔下的"Caravan Cart"没有被正确提取/确认，翻译后nut文件内容变成了	Cart = "getroottable",

line 1284 		Captain = "Sergeant",也同样原因变成了Captain = "getroottable",

**Comment by Rayforward** [comment]
scripts/config/strings.json
line190-194
	"Lindwurm",
	"Unhold",
	"Unhold",
	"Unhold",

**Comment by shabbywu** [comment]
scripts/skills/effects/sleeping_effect.nut
- "Sleeping"

**Comment by Rayforward** [comment]
scripts/contracts/contracts/roaming_beasts_contract.nut
Line191、205
"Direwolves"

**Comment by shabbywu** [comment]
> getroottable

getroottable 应该只是反编译器的问题，strings.nut 文件的文本量大，在翻译这个文件时做了额外的优化处理。

**Comment by shabbywu** [comment]
> Title = "Overview"

因为 ID 也叫 Overview，现在的翻译原理不太好微操，先忽略这个词吧

**Comment by shabbywu** [comment]
Title = "Barber"

town_barber_dialog_module.nut

**Comment by shabbywu** [comment]
this.World.TopbarDayTimeModule.showMessage("ENCAMPED", "")

scripts\states\world_state.nut

**Comment by shabbywu** [comment]
黑名单里移除 "[color=" 以方便调整语序

**Comment by shabbywu** [comment]
this.m.Name = "Charmed";
scripts\skills\effects\charmed_effect.nut

**Comment by shabbywu** [comment]
Text = "Fools."

scripts\contracts\contracts\decisive_battle_contract.nut

**Comment by shabbywu** [comment]
目前已知的所有文本都处理了. 先关闭这个 issue 了
