### ISSUE TITLE
关于等待怪物到来的问题

### ISSUE THREAD

**Issue by xblh** [shabbywu/Battle-Brothers-CN#8]
[log.zip](https://github.com/shabbywu/Battle-Brothers-CN/files/11128446/log.zip)
我在一个城市中接了女巫任务，然后在等待女巫到来的时间段我在此地扎营，等到女巫到来弹出女巫到来事件与女巫作战，在战斗中打赢了女巫，退出战斗（没有后续事件）又弹出事件与女巫作战（一直重复）除了女巫，梦魇（经测试）也会如此。（我没有在纯本体中测试，只在传奇mod中测试了）感谢大佬，大佬辛苦了。

**Comment by shabbywu** [comment]
翻了下源码(应该是 hunting_hexen_contract.nut 这文件)和历史汉化文本，有个关键词被误提取出来了，不确定会不会是因为这样导致无限循环

```
# 在开始战斗的地方
{
Text = "To arms!"
function getResult() {
    ...
    p.CombatID = "Hexen";  # 这文本被翻译了
    ...
  }
}

# 在判断战斗结束的地方

function onCombatVictory(_combatID)
{
  if(_combatID == "Hexen")
  {
	  Flags.set("IsVictory", true);
  }
}
```

在今天刚发的 0401 版本里去掉了这个词的翻译，你可以试试看。（当然我不确定会不会有新的bug

**Comment by xblh** [comment]
好的，感谢大佬，大佬辛苦了

**Comment by shabbywu** [comment]
理论上已修复，现关闭 issue
