### ISSUE TITLE
收集语序问题的词条

### ISSUE THREAD

**Issue by shabbywu** [shabbywu/Battle-Brothers-CN#82]
对于某些有语序问题的文本，目前提供了一种基于模板渲染的方案来解决语序问题。
基本原理: 
将原文的文本组装方式替换成模板渲染，通过修改模板中的文本语序，达到解决语序问题的目的。

例子:
> 原文: `"Secure " + Flags.get("DestinationName")`
> 等价的模板: `"Secure %s"`
> 译文模板: `确保 %s 的安全`   
> 模板变量 [Flags.get("DestinationName")]

语序问题需要人工确认，因此解决语序问题的文本只能人工构造。
以下是对应上述例子的 Para 词条
```json
{
	"ID": 315631954,
	"key": "\"Secure \" + Flags.get(\"DestinationName\")",
	"original": "\"Secure \" + Flags.get(\"DestinationName\")",
	"translation": "确保 %s 的安全",
	"stage": 1,
	"context": "{\n    \"sourcename\": \"scripts/contracts/contracts/investigate_cemetery_contract.nut\",\n    \"location\": \"createStates::start\",\n    \"type\": \"AddExprReplaceImpl\"\n}"
}
```

格式是 json, 其中 
- ID/stage 由 Para 自动生成
- key 和 original 是原文里对应的表达式
- translation 是译文模板
- context 是翻译器需要的上下文信息, context 是一个 序列化成字符串的 json

context 的结构
```json
{
	"sourcename": "scripts/contracts/contracts/investigate_cemetery_contract.nut",
	"location": "createStates::start",
	"type": "AddExprReplaceImpl"
}
```

其中:
- sourcename 是对应的游戏脚本路径
- location 是 original 对应的表达式出现在那个函数(如果有同名函数, 需要增加下标 [x], 例如 createScreens::getResult[6] 表示在 createScreens 函数里的第 7 个 getResult 函数
- type 固定写 AddExprReplaceImpl

附录:
- [词条收集](https://github.com/shabbywu/Battle-Brothers-CN/issues/82), 构造出来的词条在这个 issue 中回复, 需要更新到 `json/patch/` 目录下才会生效
- [反编译的汉化后的游戏原文项目地址](https://github.com/BattleBrothersGameCN/cn-scripts), 用于协助排查翻译后的语序是否准确, 每天上午8点半定时更新
- [测试版翻译器](https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v20230703), 目前只有这个版本的翻译器使用了解决语序问题的方案
- [词条生成工具(辅助)](https://service-0w0o91c8-1251690780.gz.apigw.tencentcs.com/release/tools/patch-builder.html)

**Comment by Rayforward** [comment]
https://paratranz.cn/projects/7032/strings?file=918445&task=1612

[this.World](http://this.world/).FactionManager.getFaction(this.Contract.getFaction()).addPlayerRelation([this.Const.World](http://this.const.world/).Assets.RelationCivilianContractFail * 2, 'You failed to save ' + this.Contract.m.Home.getName() + ' from barbarians out for revenge')

'You failed to save ' + this.Contract.m.Home.getName() + ' from barbarians out for revenge'

'你没能从从野蛮人的复仇中拯救' + this.Contract.m.Home.getName()

**Comment by Rayforward** [comment]
对了，词条生成器希望能做一个反向解析功能，方便下次打开时填入上次生成的错误（如果错了）词条重新修改

**Comment by shabbywu** [comment]
this 应该不影响, 你把生存的词条加到本地文本里 json/patch 目录下面，重新翻译没报错的话，就说明正常工作。

**Comment by Rayforward** [comment]
成功了，不过就是疑惑添加至para的问题，在线工具生成的代码都加好了\符号，但para用添加词条的功能时很多生成的\符号要手动去掉（同步回本地又加好了\符号）

**Comment by shabbywu** [comment]
词条还是建议用 push-to-paratranz 来推送，这样只需要在本地编辑 json 就可以了

**Comment by shabbywu** [comment]
主键值用文件名，函数位置，原文文本等组成，基本不会重复。

**Comment by shabbywu** [comment]
要去掉 \ 的话，晚点我加几个功能也行

**Comment by Rayforward** [comment]
```{
    "ID": 319280855,
    "key": "\"You failed to save \" + this.Contract.m.Home.getName() + \" from barbarians out for revenge\"",
    "original": "\"You failed to save \" + this.Contract.m.Home.getName() + \" from barbarians out for revenge\"",
    "translation": "你没能从野蛮人的复仇中救下%s",
    "stage": 5,
    "context": "{\n    \"sourcename\": \"scripts/contracts/contracts/drive_away_barbarians_contract.nut\",\n    \"location\": \"createScreens::getResult[17]\",\n    \"type\": \"AddExprReplaceImpl\"\n}"
  }```
  
  
  这段会导致翻译生成到他那个contract的时候exitstatus1，能帮忙看看吗？

**Comment by shabbywu** [comment]
> createScreens::getResult[17]

https://github.com/BattleBrothersGameCN/cn-scripts/blob/1f9214f60ef07f2736ac63922afe4c3b545edd23/nut/scripts/contracts/contracts/drive_away_barbarians_contract.nut#L643C7-L643C7

这文件总共有 18 个 getResult
需要翻译的文本在顺数的第17个 getResult，所以要写的是 `createScreens::getResult[16]`

**Comment by Rayforward** [comment]
> > createScreens::getResult[17]
> 
> https://github.com/BattleBrothersGameCN/cn-scripts/blob/1f9214f60ef07f2736ac63922afe4c3b545edd23/nut/scripts/contracts/contracts/drive_away_barbarians_contract.nut#L643C7-L643C7
> 
> 这文件总共有 18 个 getResult 需要翻译的文本在顺数的第17个 getResult，所以要写的是 `createScreens::getResult[16]`

改成16还是会在命令行到那儿的时候exitstatus1，挠头

**Comment by shabbywu** [comment]
> > > createScreens::getResult[17]
> > 
> > 
> > https://github.com/BattleBrothersGameCN/cn-scripts/blob/1f9214f60ef07f2736ac63922afe4c3b545edd23/nut/scripts/contracts/contracts/drive_away_barbarians_contract.nut#L643C7-L643C7
> > 这文件总共有 18 个 getResult 需要翻译的文本在顺数的第17个 getResult，所以要写的是 `createScreens::getResult[16]`
> 
> 改成16还是会在命令行到那儿的时候exitstatus1，挠头

仔细数一下 https://github.com/BattleBrothersGameCN/cn-scripts/blob/1f9214f60ef07f2736ac63922afe4c3b545edd23/nut/scripts/contracts/contracts/drive_away_barbarians_contract.nut#L643C7-L643C7 会发现，整个文件总共有 18 个 getResult，但是 createScreens 里面总共只有 16 个 getResult. 有2个 getResult 是这 start函数里面.🤪 

所以正确的索引是 createScreens::getResult[14]

**Comment by shabbywu** [comment]
关键的地方其实很简单，就是要准确定位到文本所在的位置.

squirrel 一个闭包作用域可以声明多个同名函数，所有声明的函数按声明顺序以 List 形式存储在闭包作用域里面。

而 `createScreens::getResult[14]` 的含义就是取名字叫 `createScreens` 的这个闭包作用域(每个函数都是一个闭包)里面的第15个名字叫getResult的函数。

严格来说可以写成 `createScreens[0]::getResult[14]`, 因为 `createScreens` 事实上也存储在一个省略的闭包里面.

所以只需要知道这个 `location` 的含义，就很容易根据源代码(.nut) 来构造相应的 `location` 了

**Comment by Rayforward** [comment]
哦哦。确实整个文件维度上的第5和第11个`getResult`在`createScreens`下第3和第5个`start`里，那我还有个问题，因为`function start`有12个，前4个在`createScreens`外面，如果要定位这第5个`getResult`，是写
`createScreens::start[2]::getResult`还是`start[6]::getResult`？（即是否一定要声明最外面的那个function闭包）

**Comment by shabbywu** [comment]
`createScreens::start[2]::getResult`

**Comment by Rayforward** [comment]
OJBK

**Comment by shabbywu** [comment]
> 也许反解析和生成para专用粘贴用格式不错

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/5237578/05c84d4b-4de4-4db2-b32a-54d4268cba28)

更新了
