### ISSUE TITLE
伤残效果无法显示

### ISSUE THREAD

**Issue by zhang-lun** [shabbywu/Battle-Brothers-CN#94]
打了补丁后,伤病效果鼠标移上去没有反应,不会显示对应的负面效果

**Comment by Rayforward** [comment]
我没有遇到过，你是用的最新版本的[bb-translator:v0.4.x](https://github.com/shabbywu/Battle-Brothers-CN/releases/tag/v20230703)吗，游戏是steam的还是gog还是其他盗版？是否用了大地图中文功能？

**Comment by shabbywu** [comment]
补充个截图看下触发方式。还有 Mod 列表也发一下。最好就是能提供 ”我的文档/BattleBrothers/log.html" 这个文件里的日志

**Comment by Rayforward** [comment]
复现了，在生成翻译文件时就有个警告：
warning!!! sourcename != clousure.sourcename ('scripts/root_state.nut' != 'data\scripts\root_state.nut')

==============

战斗时的log:

        <div class="row debug">
            <div class="entry-container">
                <div class="time">12:54:03</div>
                <div class="tag">SQ</div>
                <div class="text">游牧割喉者使用技能戳击</div>
            </div>
        </div>
        <div class="row debug">
            <div class="entry-container">
                <div class="time">12:54:04</div>
                <div class="tag">SQ</div>
                <div class="text">回合开始于：艾德穆德</div>
            </div>
        </div>
        <div class="row error">
            <div class="entry-container">
                <div class="time">12:54:11</div>
                <div class="tag">Script Error</div>
                <div class="text">the index 'ht' does not exist</div>
            </div>
            <div class="stacktrace-container">
                <div class="value-container">
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">main -> unnamedbuffer : 1</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">vargv = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">addTooltipHint -> scripts/skills/injury/injury.nut : 137</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">d = Null, ht = Table, _tooltip = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">getTooltip -> scripts/skills/injury/pierced_side_injury.nut : 49</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">ret = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">general_queryStatusEffectTooltipData ->
                            scripts/ui/screens/tooltip/tooltip_events.nut : 742</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">statusEffect = Table, entity = Table, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">
                            <Unknown> -> msu/hooks/ui/screens/tooltip/tooltip_events.nut : 30
                        </div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">general_queryStatusEffectTooltipData = Function, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row error">
            <div class="entry-container">
                <div class="time">12:54:13</div>
                <div class="tag">Script Error</div>
                <div class="text">the index 'ht' does not exist</div>
            </div>
            <div class="stacktrace-container">
                <div class="value-container">
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">main -> unnamedbuffer : 1</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">vargv = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">addTooltipHint -> scripts/skills/injury/injury.nut : 137</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">d = Null, ht = Table, _tooltip = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">getTooltip -> scripts/skills/injury/pierced_side_injury.nut : 49</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">ret = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">general_queryStatusEffectTooltipData ->
                            scripts/ui/screens/tooltip/tooltip_events.nut : 742</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">statusEffect = Table, entity = Table, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">
                            <Unknown> -> msu/hooks/ui/screens/tooltip/tooltip_events.nut : 30
                        </div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">general_queryStatusEffectTooltipData = Function, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row error">
            <div class="entry-container">
                <div class="time">12:54:14</div>
                <div class="tag">Script Error</div>
                <div class="text">the index 'ht' does not exist</div>
            </div>
            <div class="stacktrace-container">
                <div class="value-container">
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">main -> unnamedbuffer : 1</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">vargv = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">addTooltipHint -> scripts/skills/injury/injury.nut : 137</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">d = Null, ht = Table, _tooltip = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">getTooltip -> scripts/skills/injury/pierced_side_injury.nut : 49</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">ret = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">general_queryStatusEffectTooltipData ->
                            scripts/ui/screens/tooltip/tooltip_events.nut : 742</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">statusEffect = Table, entity = Table, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">
                            <Unknown> -> msu/hooks/ui/screens/tooltip/tooltip_events.nut : 30
                        </div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">general_queryStatusEffectTooltipData = Function, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row error">
            <div class="entry-container">
                <div class="time">12:54:21</div>
                <div class="tag">Script Error</div>
                <div class="text">the index 'ht' does not exist</div>
            </div>
            <div class="stacktrace-container">
                <div class="value-container">
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">main -> unnamedbuffer : 1</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">vargv = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">addTooltipHint -> scripts/skills/injury/injury.nut : 137</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">d = Null, ht = Table, _tooltip = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">getTooltip -> scripts/skills/injury/pierced_side_injury.nut : 49</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">ret = Array, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">general_queryStatusEffectTooltipData ->
                            scripts/ui/screens/tooltip/tooltip_events.nut : 742</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">statusEffect = Table, entity = Table, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                    <div class="function-container">
                        <div class="label">Function:</div>
                        <div class="value">
                            <Unknown> -> msu/hooks/ui/screens/tooltip/tooltip_events.nut : 30
                        </div>
                    </div>
                    <div class="function-container">
                        <div class="label">Variables:</div>
                        <div class="valueVar">general_queryStatusEffectTooltipData = Function, _statusEffectId =
                            injury.pierced_side, _entityId = 17801, this = Table</div>
                    </div>
                </div>
            </div>

**Comment by zhang-lun** [comment]
steam版用的最新的bb-translato release包,使用steam打开和使用翻译器打开都有这个问题
mod列表如下:
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/19149616/e7ef9f68-f60d-4831-b5da-42f3d920100d)
bug我看上边也复现了,我这里基本是必现,大部分伤残无法hover,不过好像有几个是可以显示的
伤残hover:
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/19149616/48dfa4b3-9042-459c-9bf3-a41a3b17f88a)
正常:
![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/19149616/9e9824f6-03a2-4fca-8703-bce65e9042ae)

日志我看了下只有短时间内的,我这最近没有触发伤残,可以先看看上边的日志

**Comment by shabbywu** [comment]
修复了，重新执行翻译可修复

**Comment by Rayforward** [comment]
> 修复了，重新执行翻译可修复

mod全部失效了

**Comment by shabbywu** [comment]
> > 修复了，重新执行翻译可修复
> 
> mod全部失效了

发一下 data 目录按时间排序的列表看下

**Comment by Rayforward** [comment]
> > > 修复了，重新执行翻译可修复
> > 
> > 
> > mod全部失效了
> 
> 发一下 data 目录按时间排序的列表看下

![image](https://github.com/shabbywu/Battle-Brothers-CN/assets/45681350/5d7306b4-64d9-4edb-b2fa-64f40ed3faaf)

**Comment by shabbywu** [comment]
> > > > 修复了，重新执行翻译可修复
> > > 
> > > 
> > > mod全部失效了
> > 
> > 
> > 发一下 data 目录按时间排序的列表看下
> 
> ![image](https://user-images.githubusercontent.com/45681350/253782248-5d7306b4-64d9-4edb-b2fa-64f40ed3faaf.png)

昨天顺手把文件挂载顺序调整成按修改时间排序，所以按照你这个 mod 顺序会有问题。
刚刚又调整了挂载顺序，将 **.dat** 末尾的文件的优先级放低。这样Mod就能生效了

**Comment by Rayforward** [comment]
> > > > > 修复了，重新执行翻译可修复
> > > > 
> > > > 
> > > > mod全部失效了
> > > 
> > > 
> > > 发一下 data 目录按时间排序的列表看下
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45681350/253782248-5d7306b4-64d9-4edb-b2fa-64f40ed3faaf.png)
> 
> 昨天顺手把文件挂载顺序调整成按修改时间排序，所以按照你这个 mod 顺序会有问题。 刚刚又调整了挂载顺序，将 **.dat** 末尾的文件的优先级放低。这样Mod就能生效了

请问能帮忙看下隔壁我的问题吗，搞不定这个没士气折腾语序了：
              ```{
    "ID": 319280855,
    "key": "\"You failed to save \" + this.Contract.m.Home.getName() + \" from barbarians out for revenge\"",
    "original": "\"You failed to save \" + this.Contract.m.Home.getName() + \" from barbarians out for revenge\"",
    "translation": "你没能从野蛮人的复仇中救下%s",
    "stage": 5,
    "context": "{\n    \"sourcename\": \"scripts/contracts/contracts/drive_away_barbarians_contract.nut\",\n    \"location\": \"createScreens::getResult[17]\",\n    \"type\": \"AddExprReplaceImpl\"\n}"
  }
  ```
  
  这段会导致翻译生成到他那个contract的时候exitstatus1，能帮忙看看吗？

_Originally posted by @Rayforward in https://github.com/shabbywu/Battle-Brothers-CN/issues/82#issuecomment-1635765746_

**Comment by shabbywu** [comment]
测试问题已修复, 如果还有问题再另建 issue /close
